**1.Import Libraries**

In [1]:
import folium
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import mysql.connector
from folium.plugins import HeatMap
from datetime import datetime

from IPython.display import display
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

import warnings
warnings.filterwarnings('ignore')

**3.Data Transformation or Cleaning**

In [5]:
df = pd.read_csv('individual.csv')
df1 = pd.read_csv('INDIVIDUAL_DETAILS_CORE.csv')
pd.set_option('display.max_columns',None)

In [6]:
df1.head(1)

,_URI,_CREATOR_URI_USER,_CREATION_DATE,_LAST_UPDATE_URI_USER,_LAST_UPDATE_DATE,_MODEL_VERSION,_UI_VERSION,_IS_COMPLETE,_SUBMISSION_DATE,_MARKED_AS_COMPLETE_DATE,LEARNING_PLACE,EVENT_DATE,IS_PRESENT,WORK_REGIME,MOTHER_NAME,NR_OF_HUSBAND_WIVES,DOB,FERTILITY_NR_GIRLS,HAS_EDUCATION,FERTILITY_HAS_PREV_PREGNANCIES,PLACE_OF_BIRTH,ID_EXP_STAT,DEFICIENCY_NAME,FERTILITY_NR_STILLBIRTHS,HAS_ID_CARD,MOTHER_PERM_ID,REGION,HAS_VOTER_CARD,NON_WORK_DAYS,DEVICEID,CARD_STATE,FERTILITY_NR_TWIN_ABORTIONS,HAS_BIRTH_CERTIFICATE,RELIGION,NR_OF_WIVES,WORKS_FOR_OTHERS,SECUNDARY_OCUPATION,HAS_CEDULA,FERTILITY_NR_MISCARRIAGES,HOUSE_NUMBER,REASON_TO_NOT_UPDATE,SPOUSE_NAME,FATHER_ALIVE,EDUCATION,READING_QUALITY,PROCESSED_BY_MIRTH,FERTILITY_NR_ABORTIONS,FERTILITY_NR_TWIN_OUTCOMES,HAS_PASSPORT,SECUNDARY_OCUPATION_NAME,OCUPATION_NAME,HAS_FERTILITY,FERTILITY_NR_TWIN_STILLBIRTHS,CAN_READ_WRITE,FERTILITY_NR_BOYS,EVENT_PLACE,IDENTITY_DOC_TYPE,IS_UPDATABLE,CONSENT,STOPPED_WORK_LAST_MONTH,MOTHER_ID,OCUPATION,MARITAL_STATUS,PASSPORT_EXP_STAT,RELATION_WITH_HEAD,PERM_ID,META_INSTANCE_NAME,HAS_DRIVING_LICENSE,DEFICIENCY_CAUSES_NAME,FERTILITY_NR_ALIVE_GIRLS,IDENTITY_DOC_NAME,FATHER_DEATH_DATE,NAME,MOTHER_ALIVE,ID_RECEIPT_EXP_STAT,VISIT_ID,PROCESSED_BY_SYNC,DEFICIENCY_CAUSES,FERTILITY_NR_PREGNANCIES,END,FERTILITY_NR_LIVEBIRTHS,DRIV_LICENSE_EXP_STAT,HAS_ID_RECEIPT,MOTHER_DEATH_DATE,FATHER_PERM_ID,MOTHER_TONGUE,SELF_EMPLOYED,FERTILITY_NR_TWINS_ALIVE,WIVES_ON_SAME_HOUSE,INDIVIDUAL_ID,META_INSTANCE_ID,HEAD_LIVES_HERE,MOTHER_LIVES_HERE,ROUND_NUMBER,GENDER,LOCATION_ID,FATHER_NAME,AGE,FIELD_WORKER_ID,FATHER_ID,NOTE_READING,FERTILITY_NR_TRIPLET_OUTCOMES,SPOUSE_PERM_ID,FERTILITY_NR_QUADR_OUTCOMES,CAN_TEST_READING,HAS_DEFICIENCY,DEFICIENCY,HAS_CISM_CARD,FERTILITY_NR_ALIVE_BOYS,RELATION_WITH_SUBS_HEAD,HAS_IDENTITY_DOC,START,FATHER_LIVES_HERE
0,bcgffff,uid:dss|2015-03-10T17:58:43.352+0000,2017-04-14 14:37:46.000,NaN,2017-04-14 14:37:46.000,NaN,NaN,1,2017-04-14 14:37:46.000,2017-04-14 14:37:46.000,NaN,NaN,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14 00:00:00.000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,Individual_Dtls_3506-245-07,NaN,NaN,NaN,NaN,NaN,ADINENCIA ANTONIO MUCARI,1.0,NaN,BRX000324040,1.0,NaN,NaN,2017-04-10 11:57:23.000,NaN,NaN,NaN,NaN,UNK,NaN,NaN,NaN,NaN,BRX000324007,uuid:00003329-1e19-4117-a1db-7bc43765a051,2.0,2.0,40,F,BRX000324,UNK,4.0,FWAM6,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,4.0,99.0,2017-04-10 13:56:55.000,2.0

In [7]:
df1.head(2)

,_URI,_CREATOR_URI_USER,_CREATION_DATE,_LAST_UPDATE_URI_USER,_LAST_UPDATE_DATE,_MODEL_VERSION,_UI_VERSION,_IS_COMPLETE,_SUBMISSION_DATE,_MARKED_AS_COMPLETE_DATE,LEARNING_PLACE,EVENT_DATE,IS_PRESENT,WORK_REGIME,MOTHER_NAME,NR_OF_HUSBAND_WIVES,DOB,FERTILITY_NR_GIRLS,HAS_EDUCATION,FERTILITY_HAS_PREV_PREGNANCIES,PLACE_OF_BIRTH,ID_EXP_STAT,DEFICIENCY_NAME,FERTILITY_NR_STILLBIRTHS,HAS_ID_CARD,MOTHER_PERM_ID,REGION,HAS_VOTER_CARD,NON_WORK_DAYS,DEVICEID,CARD_STATE,FERTILITY_NR_TWIN_ABORTIONS,HAS_BIRTH_CERTIFICATE,RELIGION,NR_OF_WIVES,WORKS_FOR_OTHERS,SECUNDARY_OCUPATION,HAS_CEDULA,FERTILITY_NR_MISCARRIAGES,HOUSE_NUMBER,REASON_TO_NOT_UPDATE,SPOUSE_NAME,FATHER_ALIVE,EDUCATION,READING_QUALITY,PROCESSED_BY_MIRTH,FERTILITY_NR_ABORTIONS,FERTILITY_NR_TWIN_OUTCOMES,HAS_PASSPORT,SECUNDARY_OCUPATION_NAME,OCUPATION_NAME,HAS_FERTILITY,FERTILITY_NR_TWIN_STILLBIRTHS,CAN_READ_WRITE,FERTILITY_NR_BOYS,EVENT_PLACE,IDENTITY_DOC_TYPE,IS_UPDATABLE,CONSENT,STOPPED_WORK_LAST_MONTH,MOTHER_ID,OCUPATION,MARITAL_STATUS,PASSPORT_EXP_STAT,RELATION_WITH_HEAD,PERM_ID,META_INSTANCE_NAME,HAS_DRIVING_LICENSE,DEFICIENCY_CAUSES_NAME,FERTILITY_NR_ALIVE_GIRLS,IDENTITY_DOC_NAME,FATHER_DEATH_DATE,NAME,MOTHER_ALIVE,ID_RECEIPT_EXP_STAT,VISIT_ID,PROCESSED_BY_SYNC,DEFICIENCY_CAUSES,FERTILITY_NR_PREGNANCIES,END,FERTILITY_NR_LIVEBIRTHS,DRIV_LICENSE_EXP_STAT,HAS_ID_RECEIPT,MOTHER_DEATH_DATE,FATHER_PERM_ID,MOTHER_TONGUE,SELF_EMPLOYED,FERTILITY_NR_TWINS_ALIVE,WIVES_ON_SAME_HOUSE,INDIVIDUAL_ID,META_INSTANCE_ID,HEAD_LIVES_HERE,MOTHER_LIVES_HERE,ROUND_NUMBER,GENDER,LOCATION_ID,FATHER_NAME,AGE,FIELD_WORKER_ID,FATHER_ID,NOTE_READING,FERTILITY_NR_TRIPLET_OUTCOMES,SPOUSE_PERM_ID,FERTILITY_NR_QUADR_OUTCOMES,CAN_TEST_READING,HAS_DEFICIENCY,DEFICIENCY,HAS_CISM_CARD,FERTILITY_NR_ALIVE_BOYS,RELATION_WITH_SUBS_HEAD,HAS_IDENTITY_DOC,START,FATHER_LIVES_HERE
0,bcgffff,uid:dss|2015-03-10T17:58:43.352+0000,2017-04-14 14:37:46.000,NaN,2017-04-14 14:37:46.000,NaN,NaN,1,2017-04-14 14:37:46.000,2017-04-14 14:37:46.000,NaN,NaN,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14 00:00:00.000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,Individual_Dtls_3506-245-07,NaN,NaN,NaN,NaN,NaN,ADINENCIA ANTONIO MUCARI,1.0,NaN,BRX000324040,1.0,NaN,NaN,2017-04-10 11:57:23.000,NaN,NaN,NaN,NaN,UNK,NaN,NaN,NaN,NaN,BRX000324007,uuid:00003329-1e19-4117-a1db-7bc43765a051,2.0,2.0,40,F,BRX000324,UNK,4.0,FWAM6,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,4.0,99.0,2017-04-10 13:56:55.000,2.0
1,uuid:0000041e-f924-4d70-8547-1116eb4368b2,uid:dss|2015-03-10T17:58:43.352+0000,2018-12-17 07:17:48.000,NaN,2018-12-17 07:17:48.000,20181.0,NaN,1,2018-12-17 07:17:48.000,2018-12-17 07:17:48.000,1.0,NaN,1.0,1.0,ANA ALFREDO VALOI,NaN,1992-04-02 00:00:00.000,NaN,1.0,NaN,1.0,NaN,NaN,NaN,2.0,0406-025-02,1802.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,23.0,2.0,NaN,1802-170,NaN,NaN,NaN,8.0,2.0,0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN,7.0,1.0,1.0,2.0,4BF000036002,4.0,1.0,NaN,1.0,0406-025-03,Individual_Dtls_0406-025-03,2.0,NaN,NaN,NaN,NaN,GRACA FRANCISCO MACHAVA,NaN,NaN,PHV000166043,1.0,NaN,NaN,2018-12-12 14:39:51.000,NaN,NaN,2.0,NaN,0406-025-01,22.0,1.0,NaN,NaN,4BF000036003,uuid:0000041e-f924-4d70-8547-1116eb4368b2,1.0,NaN,43,F,PHV000166,ALBINO JOAO NHAZIMO,26.0,FWIX1,4BF000036001,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2018-12-12 16:27:07.000,NaN

**3.1 Lets reduce the size of df1, its way to large**<br>
Assigning category and date on specific features reduce alot of memory

In [8]:
# Drop columns we won't use
df1 = df1.drop(columns=['_CREATOR_URI_USER', '_CREATION_DATE', '_LAST_UPDATE_URI_USER', '_MODEL_VERSION', '_UI_VERSION', '_IS_COMPLETE','_SUBMISSION_DATE',
                        '_MARKED_AS_COMPLETE_DATE','DEVICEID','PROCESSED_BY_MIRTH', 'META_INSTANCE_NAME', 'ID_RECEIPT_EXP_STAT', 'PROCESSED_BY_SYNC','META_INSTANCE_ID'])

df = df.drop(columns=['deleted','insertDate','voidDate','voidReason','status','statusMessage', 'insertBy_uuid','voidBy_uuid','collectedBy_uuid'])

In [9]:
df1 = df1.drop(columns=['_URI','_LAST_UPDATE_DATE'])

In [10]:
# df1
#Convert all object type columns in your DataFrame to category
df1 = df1.astype({col: 'category' for col in df1.select_dtypes(include='object').columns})

# Parse dates separately
parse_dates = ['START', 'END', 'DOB', 'FATHER_DEATH_DATE', 'MOTHER_DEATH_DATE']

# Apply dtypes and parse_dates to df1
df1[parse_dates] = df1[parse_dates].apply(pd.to_datetime, errors='coerce')

In [11]:
# df
#Convert all object type columns in your DataFrame to category
df = df.astype({col: 'category' for col in df.select_dtypes(include='object').columns})

# Parse dates separately
parse_dates = ['dob']

# Apply dtypes and parse_dates to df
df[parse_dates] = df[parse_dates].apply(pd.to_datetime, errors='coerce')

**3.2 Lets inner join then clean the dataset**

In [12]:
# Convert column names to lowercase for consistency
df1.columns = df1.columns.str.lower()

In [13]:
# Perform inner join on df1['perm_id'] and df['uuid']
df_merged = pd.merge(df1, df, left_on='name', right_on='firstName', how='inner')

# Display the merged dataframe
df_merged.head()

,learning_place,event_date,is_present,work_regime,mother_name,nr_of_husband_wives,dob_x,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,deficiency_name,fertility_nr_stillbirths,has_id_card,mother_perm_id,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,house_number,reason_to_not_update,spouse_name,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,secundary_ocupation_name,ocupation_name,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,mother_id,ocupation,marital_status,passport_exp_stat,relation_with_head,perm_id,has_driving_license,deficiency_causes_name,fertility_nr_alive_girls,identity_doc_name,father_death_date,name,mother_alive,visit_id,deficiency_causes,fertility_nr_pregnancies,end,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_death_date,father_perm_id,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,individual_id,head_lives_here,mother_lives_here,round_number,gender_x,location_id,father_name,age,field_worker_id,father_id,note_reading,fertility_nr_triplet_outcomes,spouse_perm_id,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,start,father_lives_here,uuid,dob_y,dobAspect,extId,firstName,gender_y,lastName,middleName,father_uuid,mother_uuid
0,NaN,NaN,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324040,NaN,NaN,2017-04-10 11:57:23,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,2.0,2.0,40,F,BRX000324,UNK,4.0,FWAM6,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,4.0,99.0,2017-04-10 13:56:55,2.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
1,NaN,NaN,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,3506-245-01,3506.0,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324046,NaN,NaN,2020-03-07 09:27:35,NaN,NaN,2.0,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,2.0,1.0,46,F,BRX000324,UNK,6.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,7.0,1.0,2020-03-07 11:27:06,1.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
2,NaN,NaN,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,3.0,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324039,NaN,NaN,2016-12-01 23:08:22,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,1.0,1.0,39,F,BRX000324,UNK,3.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,2016-12-01 18:07:59,1.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
3,NaN,NaN,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324045,NaN,NaN,2019-08-26 12:39:55,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,2.0,1.0,45,F,BRX000324,UNK,6.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,7.0,2.0,2019-08-26 14:39:29,1.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
4,NaN,NaN,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,3.0,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324048,NaN,NaN,2022-04-22 13:53:16,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,1.0,1.0,48,F,BRX000324,UNK,9.0,FWTD1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,2022-04-22 15:52:50,2.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b

**3.3 Lets clean the dataset**

In [14]:
'''Lets create a copy of our progress'''
clean = df_merged.copy()

In [15]:
#Info
clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2101091 entries, 0 to 2101090
Columns: 107 entries, learning_place to mother_uuid
dtypes: category(30), datetime64[ns](4), float64(71), int64(1), object(1)
memory usage: 1.5+ GB

In [16]:
#Describe
clean.describe()

,learning_place,is_present,work_regime,nr_of_husband_wives,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,fertility_nr_stillbirths,has_id_card,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,reason_to_not_update,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,ocupation,marital_status,passport_exp_stat,relation_with_head,has_driving_license,fertility_nr_alive_girls,mother_alive,deficiency_causes,fertility_nr_pregnancies,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,head_lives_here,mother_lives_here,round_number,age,note_reading,fertility_nr_triplet_outcomes,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,father_lives_here,dobAspect,middleName
count,752122.000000,1.813125e+06,764347.000000,3.224170e+05,79695.000000,1.107735e+06,111775.000000,1.943205e+06,654639.000000,79695.000000,1.418713e+06,2.099224e+06,979203.000000,14322.000000,529863.000000,79695.000000,1.418713e+06,1.184474e+06,250091.000000,209763.000000,899603.000000,1.418713e+06,79695.000000,156008.000000,887637.000000,1.418715e+06,240276.000000,79695.000000,79695.000000,1.418713e+06,584000.000000,79695.000000,1.581188e+06,79695.000000,797976.000000,1.418713e+06,1.969135e+06,1.943206e+06,1.032006e+06,1.032006e+06,1.163014e+06,73211.000000,1.865289e+06,979203.000000,61710.000000,887637.000000,29221.000000,79695.000000,79695.000000,39725.000000,1.418713e+06,1.073030e+06,554584.000000,79695.000000,0.0,1.943205e+06,805575.000000,2.101091e+06,1.969141e+06,0.0,3227.000000,3227.000000,446853.000000,1.943206e+06,29221.000000,790266.000000,62590.000000,93778.000000,1.813122e+06,756746.000000,359680.000000,0.0
mean,1.027143,1.314936e+00,1.274434,1.294137e+04,1.781617,1.166044e+00,1.287005,2.024486e+00,1.057534,0.083343,1.538568e+00,2.857057e+03,1.298701,54.349602,1.415889,0.014342,1.943138e+00,7.476608e+00,1.114058,1.048655,20.261957,1.327732e+00,0.165556,1.340117,1.710099,1.070129e+01,1.555981,0.036928,0.059966,1.948396e+00,1.904168,0.016074,1.308321e+00,1.782584,1.288903,7.412608e+00,1.079228e+00,1.935977e+00,1.986122e+00,1.273623e+01,2.868219e+00,1.289096,4.863310e+00,1.959431,1.900178,1.147935,7.625269,4.897835,3.564201,1.041989,1.986268e+00,2.457804e+01,1.233144,0.238698,NaN,1.048259e+00,1.195829,4.335280e+01,2.475295e+01,NaN,0.297800,0.278277,1.526325,1.984962e+00,23.833476,1.292555,1.820211,5.856011,2.006746e+00,1.511084,1.142071,NaN
std,1.555128,4.644907e-01,0.446229,3.286303e+06,1.621983,3.721205e-01,0.452366,4.527230e+00,0.232860,1.304103,4.985104e-01,1.037277e+03,0.457689,555.719078,0.760234,0.991574,2.315790e-01,1.625665e+01,2.064308,0.234973,13.661670,4.693866e-01,1.539720,3.050161,7.761601,1.637975e+01,0.629580,1.369517,1.065409,2.212259e-01,0.294361,0.989406,4.617999e-01,1.612263,2.552225,2.201436e+01,2.700939e-01,9.459350e+00,1.169840e-01,2.166475e+01,1.597489e+00,0.453346,1.046050e+01,0.197289,1.214084,3.294968,22.279806,9.712461,2.577801,0.200566,1.163770e-01,1.537440e+01,0.620990,0.949963,NaN,2.143140e-01,0.396838,3.054737e+00,2.056373e+01,NaN,4.895587,4.893221,2.416034,1.217021e-01,36.549769,0.454936,1.185208,14.099870,8.794110e+00,0.499877,0.349123,NaN
min,1.000000,1.000000e+00,1.000000,0.000000e+00,0.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,0.000000,1.000000e+00,1.010000e+02,1.000000,0.000000,1.000000,0.000000,1.000000e+00,1.000000e+00,0.000000,1.000000,1.000000,1.000000e+00,0.000000,1.000000,1.000000,1.000000e+00,1.000000,0.000000,0.000000,1.000000e+00,1.000000,0.000000,1.000000e+00,0.000000,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,0.000000,NaN,1.000000e+00,1.000000,3.800000e+01,-8.000000e+00,NaN,0.000000,0.000000,1.000000,1.000000e+00,1.000000,1.000000,0.000000,0.000000,1.000000e+00,1.000000,1.000000,NaN
25%,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,0.000000,1.000000e+00,2.502000e+03,1.000000,4.000000,1.000000,0.000000,2.000000e+00,2.000000e+00,1.000000,1.000000,23.000000,1.000000e+00,0.000000,1.000000,1.000000,4.000000e+00,1.000000,0.000000,0.000000,2.000000e+00,2.000000,0.000000,1.000000e+00,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000e+00,2.200000e+01,1.000000,0.000000,NaN,1.000000e+00,1.000000,4.100000e+01,9.000000e+00,NaN,0.000000,0.000000,1.000000,2.000000e+00,5.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000,NaN
50%,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,0.000000,2.000000e+00,3.209000e+03,1.000000,8.000000,1.000000,0.000000,2.000000e+00,6.000000e+00,1.000000,1.000000,23.000000,1.000000e+00,0.000000,1.000000,1.000000,8.000000e+00,1.000000,0.000000,0.000000,2.000000e+00,2.000000,0.000000,1.000000e+00,1.000000,1.000000,2.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,1.000000,3.000000e+00,2.000000,2.000000,1.000000,2.000000,3.000000,3.000000,1.000000,2.000000e+00,2.200000e+01,1.000000,0.000000,NaN,1.000000e+00,1.000000,4.400000e+01,1.900000e+01,NaN,0.000000,0.000000,1.000000,2.000000e+00,7.000000,1.000000,2.000000,3.000000,1.000000e+00,2.000000,1.000000,NaN
75%,1.000000,2.000000e+00,2.000000,1.000000e+00,3.000000,1.000000e+00,2.000000,1.000000e+00,1.000000,0.000000,2.000000e+00,3.610000e+03,2.000000,30.000000,1.000000,0.000000,2.000000e+00,6.000000e+00,1.000000,1.000000,23.000000,2.000000e+00,0.000000,1.000000,1.000000,1.100000e+01,2.000000,0.000000,0.000000,2.000000e+00,2.000000,0.000000,2.000000e+00,3.000000,1.000000,2.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.100000e+01,3.000000e+00,2.000000,4.000000e+00,2.000000,3.000000,1.000000,2.000000,5.000000,5.000000,1.000000,2.000000e+00,2.300000e+01,1.000000,0.000000,NaN,1.000000e+00,1.000000,4.600000e+01,3.700000e+01,NaN,0.000000,0.000000,2.000000,2.000000e+00,9.000000,2.000000,2.000000,4.000000,1.000000e+00,2.000000,1.000000,NaN
max,98.000000,2.000000e+00,2.000000,8.504459e+08,13.000000,2.000000e+00,2.000000,9.900000e+01,2.000000,88.000000,2.000000e+00,3.927000e+03,2.000000,25555.000000,3.000000,88.000000,2.000000e+00,9.900000e+01,280.000000,3.000000,98.000000,2.000000e+00,88.000000,99.000000,99.000000,9.800000e+01,3.000000,88.000000,88.000000,2.000000e+00,2.000000,88.000000,2.000000e+00,88.000000,98.000000,9.800000e+01,2.000000e+00,9.900000e+01,2.000000e+00,9.800000e+01,6.000000e+00,2.000000,9.800000e+01,2.000000,10.000000,99.000000,98.000000,99.000000,88.000000,2.000000,2.000000e+00,9.800000e+01,3.000000,15.000000,NaN,2.000000e+00,2.000000,4.800000e+01,2.014000e+03,NaN,88.000000,88.000000,99.000000,2.000000e+00,98.000000,2.000000,10.000000,98.000000,9.900000e+01,2.000000,2.000000,NaN

In [17]:
clean.isnull().sum()

learning_place    1348969
event_date        1279156
is_present         287966
work_regime       1336744
mother_name           976
                   ...
gender_y                0
lastName                0
middleName        2101091
father_uuid             7
mother_uuid             0
Length: 107, dtype: int64

### `1.Lets convert some numeric features to categorical:`

**`Learning Place:`**<br>
Above its the actual feartures and their assigned tags:
- 1	Na Escola
- 2	Creche
- 3	Em casa
- 4	Na Igreja
- 98	Outro

In [18]:
clean['learning_place'].describe()

count    752122.000000
mean          1.027143
std           1.555128
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          98.000000
Name: learning_place, dtype: float64

In [19]:
clean['learning_place'].value_counts(dropna=False)

NaN     1348969
1.0      751042
3.0         551
2.0         208
98.0        193
4.0         128
Name: learning_place, dtype: int64

In [20]:
'''Dictionary for mapping values'''
clean['learning_place'] = clean['learning_place'].replace({
    1.0: 'Na Escola',
    2.0: 'Creche',
    3.0: 'Em casa',
    4.0: 'Na Igreja',
    98.0: 'Outro'
})

# Replace numeric vales with corresponding names, NaNs will remain unchanged
# clean['learning_place'] =  clean['learning_place'].map(learning_place_mapping)

# Remove rows with zero counts (if any)
clean = clean[clean['learning_place'] != 0]

# Now you can check the value counts
clean['learning_place'].value_counts(dropna=False)

NaN          1348969
Na Escola     751042
Em casa          551
Creche           208
Outro            193
Na Igreja        128
Name: learning_place, dtype: int64

**`place_of_birth:`**
- 1 Distrito da Manhiça
- 2	Província de Maputo
- 3	Cidade de Maputo 
- 4	Cidade da Matola
- 5	Gaza
- 6	Inhambane
- 7	Sofala
- 8	Manica
- 9	Tete
- 10	Zambézia
- 11	Nampula
- 12	Cabo-Delgado
- 13	Niassa
- 14	Africa do Sul
- 15	Swazilandia
- 16	Outro país Africano
- 17	Europa
- 18	Ásia
- 19	América
- 98	Outro
- 88	Não sabe
- 99	Recusa-se a responder

In [21]:
clean['place_of_birth'].describe()

count    1.943205e+06
mean     2.024486e+00
std      4.527230e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      9.900000e+01
Name: place_of_birth, dtype: float64

In [22]:
clean['place_of_birth'].value_counts(dropna=False).head()

1.0    1583537
NaN     157886
5.0      86302
2.0      73938
6.0      60688
Name: place_of_birth, dtype: int64

In [23]:
'''Dictionary for mapping values'''
clean['place_of_birth'] = clean['place_of_birth'].replace({
    1: 'Distrito da Manhiça', 2: 'Província de Maputo',
    3: 'Cidade de Maputo', 4: 'Cidade da Matola',
    5: 'Gaza', 6: 'Inhambane', 
    7: 'Sofala', 8: 'Manica',
    9: 'Tete', 10: 'Zambézia',
    11: 'Nampula',
    12: 'Cabo-Delgado',
    13: 'Niassa',
    14: 'Africa do Sul',
    15: 'Swazilandia',
    16: 'Outro país Africano',
    17: 'Europa',
    18: 'Ásia',
    19: 'América',
    98: 'Outro',
    88: 'Não sabe',
    99: 'Recusa-se a responder'
})

# Remove rows with zero counts (if any)
clean = clean[clean['place_of_birth'] != 0]

# Now you can check the value counts
# clean['place_of_birth'].value_counts(dropna=False)

**`Religions:`**<br>
- 1	Católica
- 2	Protestante/Anglicana
- 3	Cristão indeterminada
- 4	Islamica
- 5	Hindus
- 6	Zione/ Sião
- 7	Animistas
- 8	Ateus
- 9	Evangelica
- 98	Outro
- 88	Não sabe
- 99	Recusa-se a responder

In [24]:
clean['religion'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: religion
Non-Null Count    Dtype
--------------    -----
1184474 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [25]:
clean['religion'].value_counts(dropna=False)

NaN     916617
6.0     400715
2.0     289987
3.0     138512
9.0     114372
1.0     102577
8.0      85322
98.0     34109
4.0      11779
7.0       3331
88.0      2456
5.0       1253
99.0        61
Name: religion, dtype: int64

In [26]:
clean['religion'].unique()

array([nan,  2.,  6.,  9., 98.,  3.,  8.,  1.,  7., 88.,  4.,  5., 99.])

In [27]:
'''Dictionary for mapping values'''
clean['religion'] = clean['religion'].replace({
    1: 'Católica',
    2: 'Protestante/Anglicana',
    3: 'Cristão indeterminada',
    4: 'Islamica',
    5: 'Hindus',
    6: 'Zione/ Sião',
    7: 'Animistas',
    8: 'Ateus',
    9: 'Evangelica',
    98: 'Outro',
    88: 'Não sabe',
    99: 'Recusa-se a responder'
})

# Remove rows with zero counts (if any)
clean = clean[clean['religion'] != 0]

# Now you can check the value counts
clean['religion'].value_counts(dropna=False)

NaN                      916617
Zione/ Sião              400715
Protestante/Anglicana    289987
Cristão indeterminada    138512
Evangelica               114372
Católica                 102577
Ateus                     85322
Outro                     34109
Islamica                  11779
Animistas                  3331
Não sabe                   2456
Hindus                     1253
Recusa-se a responder        61
Name: religion, dtype: int64

**`Secundary_ocupation:`**<br>
- 1	Camponês	
- 2	Pescador	
- 3	Carvoeiro/lenhador	
- 4	Vendedores fixos	
- 5	Comerciantes	
- 6	Vendedores ambulantes	
- 7	Guardas/Seguranças	
- 8	Pessoal da saude	
- 9	Estudante	
- 10	Professor	
- 11	Militares/Policias	
- 12	Carpinteiro/Electricista	
- 13	Serralheiro/Pedreiro	
- 14	Incapacitado	
- 15	Voluntário	
- 16	Religioso	
- 17	Reformado/pensionista	
- 18	Empregado doméstico	
- 19	Trabalhador na RSA	
- 20	Mineiro na RSA	
- 21	Trabalhador na açucareira de Xinavane	
- 22	Trabalhador na açucareira de Maragra	
- 23	Não tem	
- 98	Outro

In [28]:
clean['secundary_ocupation'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: secundary_ocupation
Non-Null Count   Dtype
--------------   -----
899603 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [29]:
clean['secundary_ocupation'].describe()

count    899603.000000
mean         20.261957
std          13.661670
min           1.000000
25%          23.000000
50%          23.000000
75%          23.000000
max          98.000000
Name: secundary_ocupation, dtype: float64

In [30]:
clean['secundary_ocupation'].unique()

array([nan, 23.,  9.,  1., 98.,  4., 18., 14., 21.,  3., 10., 17., 15.,
        7., 22.,  2., 13.,  5., 16.,  6.,  8., 12., 19., 11., 20.])

In [31]:
clean['secundary_ocupation'].value_counts(dropna=False)

NaN     1201488
23.0     661901
1.0      120721
18.0      26568
9.0       18130
98.0      17682
4.0       13947
5.0        6039
3.0        5996
15.0       4458
13.0       4168
22.0       3412
17.0       3159
21.0       2721
2.0        2159
14.0       1722
6.0        1575
7.0        1083
10.0       1068
16.0        875
12.0        831
19.0        456
8.0         443
11.0        443
20.0         46
Name: secundary_ocupation, dtype: int64

In [32]:
'''Dictionary for mapping values'''
clean['secundary_ocupation'] = clean['secundary_ocupation'].replace({
    1: 'Camponês',
    2: 'Pescador',
    3: 'Carvoeiro/lenhador',
    4: 'Vendedores fixos',
    5: 'Comerciantes',
    6: 'Vendedores ambulantes',
    7: 'Guardas/Seguranças',
    8: 'Pessoal da saude',
    9: 'Estudante',
    10: 'Professor',
    11: 'Militares/Policias',
    12: 'Carpinteiro/Electricista',
    13: 'Serralheiro/Pedreiro',
    14: 'Incapacitado',
    15: 'Voluntário',
    16: 'Religioso',
    17: 'Reformado/pensionista',
    18: 'Empregado doméstico',
    19: 'Trabalhador na RSA',
    20: 'Mineiro na RSA',
    21: 'Trabalhador na açucareira de Xinavane',
    22: 'Trabalhador na açucareira de Maragra',
    23: 'Não tem',
    98: 'Outro'
})

# Remove rows with zero counts (if any)
clean = clean[clean['secundary_ocupation'] != 0]

# Now you can check the value counts
clean['secundary_ocupation'].value_counts(dropna=False)

NaN                                      1201488
Não tem                                   661901
Camponês                                  120721
Empregado doméstico                        26568
Estudante                                  18130
Outro                                      17682
Vendedores fixos                           13947
Comerciantes                                6039
Carvoeiro/lenhador                          5996
Voluntário                                  4458
Serralheiro/Pedreiro                        4168
Trabalhador na açucareira de Maragra        3412
Reformado/pensionista                       3159
Trabalhador na açucareira de Xinavane       2721
Pescador                                    2159
Incapacitado                                1722
Vendedores ambulantes                       1575
Guardas/Seguranças                          1083
Professor                                   1068
Religioso                                    875
Carpinteiro/Electricista                     831
Trabalhador na RSA                           456
Pessoal da saude                             443
Militares/Policias                           443
Mineiro na RSA                                46
Name: secundary_ocupation, dtype: int64

**`Ocupation:`<br>**
- 1	Camponês
- 2	Pescador
- 3	Carvoeiro/lenhador
- 4	Vendedores fixos
- 5	Comerciantes
- 6	Vendedores ambulantes
- 7	Guardas/Seguranças
- 8	Pessoal da saude
- 9	Estudante
- 10	Professor
- 11	Militares/Policias
- 12	Carpinteiro/Electricista
- 13	Serralheiro/Pedreiro
- 14	Incapacitado
- 15	Voluntário
- 16	Religioso
- 17	Reformado/pensionista
- 18	Empregado doméstico
- 19	Trabalhador na RSA
- 20	Mineiro na RSA
- 21	Trabalhador na açucareira de Xinavane
- 22	Trabalhador na açucareira de Maragra
- 23	Não trabalha
- 98	Outro

In [33]:
clean['ocupation'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: ocupation
Non-Null Count    Dtype
--------------    -----
1032006 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [34]:
clean['ocupation'].describe()

count    1.032006e+06
mean     1.273623e+01
std      2.166475e+01
min      1.000000e+00
25%      1.000000e+00
50%      3.000000e+00
75%      2.100000e+01
max      9.800000e+01
Name: ocupation, dtype: float64

In [35]:
clean['ocupation'].unique()

array([nan,  4.,  6.,  9.,  1., 15., 23.,  7., 22., 14., 98.,  8., 12.,
       13., 21., 18., 10., 17.,  2.,  5., 11.,  3., 19., 16., 20.])

In [36]:
clean['ocupation'].value_counts(dropna=False)

NaN     1069085
1.0      509308
23.0     132403
9.0       60177
21.0      58786
98.0      53049
22.0      36082
4.0       31903
13.0      23087
18.0      21550
5.0       19947
10.0      13905
15.0      11767
17.0      11375
7.0       10610
3.0        7489
8.0        6176
11.0       5007
2.0        4846
14.0       4364
6.0        3664
19.0       2750
12.0       2723
16.0        852
20.0        186
Name: ocupation, dtype: int64

In [37]:
'''Dictionary for mapping values'''
clean['ocupation'] = clean['ocupation'].replace({
    1: 'Camponês',
    2: 'Pescador',
    3: 'Carvoeiro/lenhador',
    4: 'Vendedores fixos',
    5: 'Comerciantes',
    6: 'Vendedores ambulantes',
    7: 'Guardas/Seguranças',
    8: 'Pessoal da saude',
    9: 'Estudante',
    10: 'Professor',
    11: 'Militares/Policias',
    12: 'Carpinteiro/Electricista',
    13: 'Serralheiro/Pedreiro',
    14: 'Incapacitado',
    15: 'Voluntário',
    16: 'Religioso',
    17: 'Reformado/pensionista',
    18: 'Empregado doméstico',
    19: 'Trabalhador na RSA',
    20: 'Mineiro na RSA',
    21: 'Trabalhador na açucareira de Xinavane',
    22: 'Trabalhador na açucareira de Maragra',
    23: 'Não trabalha',
    98: 'Outro'
})

# Remove rows with zero counts (if any)
clean = clean[clean['ocupation'] != 0]

# Now you can check the value counts
clean['ocupation'].value_counts(dropna=False)

NaN                                      1069085
Camponês                                  509308
Não trabalha                              132403
Estudante                                  60177
Trabalhador na açucareira de Xinavane      58786
Outro                                      53049
Trabalhador na açucareira de Maragra       36082
Vendedores fixos                           31903
Serralheiro/Pedreiro                       23087
Empregado doméstico                        21550
Comerciantes                               19947
Professor                                  13905
Voluntário                                 11767
Reformado/pensionista                      11375
Guardas/Seguranças                         10610
Carvoeiro/lenhador                          7489
Pessoal da saude                            6176
Militares/Policias                          5007
Pescador                                    4846
Incapacitado                                4364
Vendedores ambulantes                       3664
Trabalhador na RSA                          2750
Carpinteiro/Electricista                    2723
Religioso                                    852
Mineiro na RSA                               186
Name: ocupation, dtype: int64

**`Reason_to_not_update:`<br>**
- 1	O membro emigrou para ouro agregado não localizável		
- 2	Falta de informante com informação credível		
- 99	Recusa

In [38]:
clean['reason_to_not_update'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: reason_to_not_update
Non-Null Count   Dtype
--------------   -----
156008 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [39]:
clean['reason_to_not_update'].describe()

count    156008.000000
mean          1.340117
std           3.050161
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          99.000000
Name: reason_to_not_update, dtype: float64

In [40]:
clean['reason_to_not_update'].unique()

array([nan,  1.,  2., 99.])

In [41]:
clean['reason_to_not_update'].value_counts(dropna=False)

NaN     1945083
1.0      117400
2.0       38459
99.0        149
Name: reason_to_not_update, dtype: int64

In [42]:
'''Dictionary for mapping values'''
clean['reason_to_not_update'] = clean['reason_to_not_update'].replace({
    1: 'O membro emigrou para ouro agregado não localizável',
    2: 'Falta de informante com informação credível',
    99: 'Recusa'
})

# Remove rows with zero counts (if any)
clean = clean[clean['reason_to_not_update'] != 0]

# Now you can check the value counts
clean['reason_to_not_update'].value_counts(dropna=False)

NaN                                                    1945083
O membro emigrou para ouro agregado não localizável     117400
Falta de informante com informação credível              38459
Recusa                                                     149
Name: reason_to_not_update, dtype: int64

**`Education:`**
- 1	Analfabeto / Nenhuma / Não escolarizado
- 2	Alfabetização 1º
- 3	Alfabetização 2º
- 4	Alfabetização 3º
- 5	1ª Classe
- 6	2ª Classe
- 7	3ª Classe
- 8	4ª Classe
- 9	5ª Classe
- 10	6ª Classe
- 11	7ª Classe
- 12	8ª Classe
- 13	9ª Classe
- 14	10ª Classe
- 15	11ª Classe
- 16	12ª Classe
- 17	Ensino técnico elementar
- 18	Ensino técnico básico 
- 19	Ensino técnico médio
- 20	Bacharel
- 21	Licenciatura
- 22	Mestrado
- 23	Doutoramento
- 98	Outro
- 88	Não sabe

In [43]:
clean['education'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: education
Non-Null Count    Dtype
--------------    -----
1418715 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [44]:
clean['education'].describe()

count    1.418715e+06
mean     1.070129e+01
std      1.637975e+01
min      1.000000e+00
25%      4.000000e+00
50%      8.000000e+00
75%      1.100000e+01
max      9.800000e+01
Name: education, dtype: float64

In [45]:
clean['education'].unique()

array([nan,  6.,  8., 88.,  9.,  3.,  2., 10., 13., 11.,  7., 16.,  5.,
       14.,  4.,  1., 12., 98., 15., 19., 18., 21., 20., 22., 17., 23.])

In [46]:
clean['education'].value_counts(dropna=False)

NaN     682376
2.0     173374
11.0    114828
8.0     106630
9.0      98033
6.0      94097
4.0      94048
7.0      89347
10.0     87571
1.0      85115
3.0      84158
12.0     71484
5.0      67704
13.0     56905
14.0     56208
88.0     55965
16.0     48525
15.0     23442
21.0      4891
19.0      4320
98.0       725
18.0       661
20.0       228
17.0       201
22.0       154
23.0       101
Name: education, dtype: int64

In [47]:
'''Dictionary for mapping values'''
clean['education'] = clean['education'].replace({
    1: 'Analfabeto / Nenhuma / Não escolarizado',
    2: 'Alfabetização 1º',
    3: 'Alfabetização 2º',
    4: 'Alfabetização 3º',
    5: '1ª Classe',
    6: '2ª Classe',
    7: '3ª Classe',
    8: '4ª Classe',
    9: '5ª Classe',
    10: '6ª Classe',
    11: '7ª Classe',
    12: '8ª Classe',
    13: '9ª Classe',
    14: '10ª Classe',
    15: '11ª Classe',
    16: '12ª Classe',
    17: 'Ensino técnico elementar',
    18: 'Ensino técnico básico',
    19: 'Ensino técnico médio',
    20: 'Bacharel',
    21: 'Licenciatura',
    22: 'Mestrado',
    23: 'Doutoramento',
    98: 'Outro',
    88: 'Não sabe'
})

# Remove rows with zero counts (if any)
clean = clean[clean['education'] != 0]

# Now you can check the value counts
clean['education'].value_counts(dropna=False)

NaN                                        682376
Alfabetização 1º                           173374
7ª Classe                                  114828
4ª Classe                                  106630
5ª Classe                                   98033
2ª Classe                                   94097
Alfabetização 3º                            94048
3ª Classe                                   89347
6ª Classe                                   87571
Analfabeto / Nenhuma / Não escolarizado     85115
Alfabetização 2º                            84158
8ª Classe                                   71484
1ª Classe                                   67704
9ª Classe                                   56905
10ª Classe                                  56208
Não sabe                                    55965
12ª Classe                                  48525
11ª Classe                                  23442
Licenciatura                                 4891
Ensino técnico médio                         4320
Outro                                         725
Ensino técnico básico                         661
Bacharel                                      228
Ensino técnico elementar                      201
Mestrado                                      154
Doutoramento                                  101
Name: education, dtype: int64

**`Event Place:`<br>**
- 1	Distrito da Manhiça
- 2	Maputo
- 3	Matola
- 4	Outras Provincias
- 5	RSA
- 98	Outros Paises

In [48]:
clean['event_place'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: event_place
Non-Null Count   Dtype
--------------   -----
797976 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [49]:
clean['event_place'].describe()

count    797976.000000
mean          1.288903
std           2.552225
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          98.000000
Name: event_place, dtype: float64

In [50]:
clean['event_place'].unique()

array([nan,  4.,  1.,  2.,  3.,  5., 98.])

In [51]:
clean['event_place'].value_counts(dropna=False)

NaN     1303115
1.0      711275
4.0       41614
2.0       39825
5.0        3496
3.0        1257
98.0        509
Name: event_place, dtype: int64

In [52]:
'''Dictionary for mapping values'''
clean['event_place'] = clean['event_place'].replace({
    1: 'Distrito da Manhiça',
    2: 'Maputo',
    3: 'Matola',
    4: 'Outras Provincias',
    5: 'RSA',
    98: 'Outros Paises'

})

# Remove rows with zero counts (if any)
clean = clean[clean['event_place'] != 0]

# Now you can check the value counts
clean['event_place'].value_counts(dropna=False)

NaN                    1303115
Distrito da Manhiça     711275
Outras Provincias        41614
Maputo                   39825
RSA                       3496
Matola                    1257
Outros Paises              509
Name: event_place, dtype: int64

**`Marital status:`**<br>
- 1	Solteiro (nunca viveu maritalmente)	
- 2	Casado	
- 3	União-de-facto	
- 4	Divorciado	
- 5	Separado	
- 6	Viuvo

In [53]:
clean['marital_status'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: marital_status
Non-Null Count    Dtype
--------------    -----
1163014 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [54]:
clean['marital_status'].describe()

count    1.163014e+06
mean     2.868219e+00
std      1.597489e+00
min      1.000000e+00
25%      1.000000e+00
50%      3.000000e+00
75%      3.000000e+00
max      6.000000e+00
Name: marital_status, dtype: float64

In [55]:
clean['marital_status'].unique()

array([nan,  1.,  3.,  5.,  2.,  6.,  4.])

In [56]:
clean['marital_status'].value_counts(dropna=False)

NaN    938077
3.0    546831
1.0    350905
6.0    126601
5.0    102155
2.0     36044
4.0       478
Name: marital_status, dtype: int64

In [57]:
'''Dictionary for mapping values'''
clean['marital_status'] = clean['marital_status'].replace({
    1: 'Solteiro (nunca viveu maritalmente)',
    2: 'Casado',
    3: 'União-de-facto',
    4: 'Divorciado',
    5: 'Separado',
    6: 'Viuvo'

})

# Remove rows with zero counts (if any)
clean = clean[clean['marital_status'] != 0]

# Now you can check the value counts
clean['marital_status'].value_counts(dropna=False)

NaN                                    938077
União-de-facto                         546831
Solteiro (nunca viveu maritalmente)    350905
Viuvo                                  126601
Separado                               102155
Casado                                  36044
Divorciado                                478
Name: marital_status, dtype: int64

**`Relation_with_head`**<br>
- 1	O Proprio chefe
- 2	Esposo/a
- 3	Filho/a
- 4	Irmao/a
- 5	Pai/mãe
- 6	Nora
- 7	Cunhado/a
- 8	Tio/a
- 9	Neto/a
- 10	Enteado
- 11	Adoptado/a
- 12	Primo/a
- 13	Sobrinho/a
- 14	Sem parentesco 
- 98	Outro

In [58]:
clean['relation_with_head'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: relation_with_head
Non-Null Count    Dtype
--------------    -----
1865289 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [59]:
clean['relation_with_head'].describe()

count    1.865289e+06
mean     4.863310e+00
std      1.046050e+01
min      1.000000e+00
25%      1.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      9.800000e+01
Name: relation_with_head, dtype: float64

In [60]:
clean['relation_with_head'].unique()

array([nan,  3.,  1., 13., 10.,  4.,  2.,  7.,  9., 98., 14.,  6.,  5.,
        8., 12., 11.])

In [61]:
clean['relation_with_head'].value_counts(dropna=False)

3.0     711157
1.0     480404
9.0     251003
NaN     235802
2.0     199490
6.0      49036
13.0     48896
10.0     30354
4.0      30159
98.0     21113
5.0      17572
14.0     12302
7.0       8494
12.0      3458
8.0       1640
11.0       211
Name: relation_with_head, dtype: int64

In [62]:
'''Dictionary for mapping values'''
clean['relation_with_head'] = clean['relation_with_head'].replace({
    1: 'O Proprio chefe',
    2: 'Esposo/a',
    3: 'Filho/a',
    4: 'Irmao/a',
    5: 'Pai/mãe',
    6: 'Nora',
    7: 'Cunhado/a',
    8: 'Tio/a',
    9: 'Neto/a',
    10: 'Enteado',
    11: 'Adoptado/a',
    12: 'Primo/a',
    13: 'Sobrinho/a',
    14: 'Sem parentesco',
    98: 'Outro'

})

# Remove rows with zero counts (if any)
clean = clean[clean['relation_with_head'] != 0]

# Now you can check the value counts
clean['relation_with_head'].value_counts(dropna=False)

Filho/a            711157
O Proprio chefe    480404
Neto/a             251003
NaN                235802
Esposo/a           199490
Nora                49036
Sobrinho/a          48896
Enteado             30354
Irmao/a             30159
Outro               21113
Pai/mãe             17572
Sem parentesco      12302
Cunhado/a            8494
Primo/a              3458
Tio/a                1640
Adoptado/a            211
Name: relation_with_head, dtype: int64

**`Deficiency:`**<br>
- 1	Cego
- 2	Surdo
- 3	Braço amputado
- 4	Braço atrofiado
- 5	Perna amputada
- 6	Perna atrofiado
- 7	Paralesia Infantil(polio)
- 8	Paralesia Adulta(trombose)
- 9	Mental
- 98	Outro

In [63]:
clean['deficiency'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: deficiency
Non-Null Count  Dtype
--------------  -----
29221 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [64]:
clean['deficiency'].describe()

count    29221.000000
mean        23.833476
std         36.549769
min          1.000000
25%          5.000000
50%          7.000000
75%          9.000000
max         98.000000
Name: deficiency, dtype: float64

In [65]:
clean['deficiency'].unique()

array([nan,  8.,  2.,  7.,  6.,  4., 98.,  9.,  5.,  1.,  3.])

In [66]:
clean['deficiency'].value_counts(dropna=False)

NaN     2071870
98.0       5691
6.0        5131
9.0        4602
8.0        3195
7.0        2808
1.0        2655
4.0        1833
2.0        1435
5.0        1415
3.0         456
Name: deficiency, dtype: int64

In [67]:
'''Dictionary for mapping values'''
clean['deficiency'] = clean['deficiency'].replace({
    1: 'Cego',
    2: 'Surdo',
    3: 'Braço amputado',
    4: 'Braço atrofiado',
    5: 'Perna amputada',
    6: 'Perna atrofiado',
    7: 'Paralesia Infantil(polio)',
    8: 'Paralesia Adulta(trombose)',
    9: 'Mental',
    98: 'Outro'

})

# Remove rows with zero counts (if any)
clean = clean[clean['deficiency'] != 0]

# Now you can check the value counts
clean['deficiency'].value_counts(dropna=False)

NaN                           2071870
Outro                            5691
Perna atrofiado                  5131
Mental                           4602
Paralesia Adulta(trombose)       3195
Paralesia Infantil(polio)        2808
Cego                             2655
Braço atrofiado                  1833
Surdo                            1435
Perna amputada                   1415
Braço amputado                    456
Name: deficiency, dtype: int64

**`Deficiency_causes:`**<br>
- 1	Nascença
- 2	Doença
- 3	Minas/guerra
- 4	Serviço militar
- 5	Acidente de trabalho
- 6	Acidente de viação
- 98	Outros

In [68]:
clean['deficiency_causes'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: deficiency_causes
Non-Null Count  Dtype
--------------  -----
29221 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [69]:
clean['deficiency_causes'].describe()

count    29221.000000
mean         7.625269
std         22.279806
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max         98.000000
Name: deficiency_causes, dtype: float64

In [70]:
clean['deficiency_causes'].value_counts(dropna=False)

NaN     2071870
2.0       16156
1.0        7578
98.0       1669
6.0        1626
5.0        1388
3.0         546
4.0         258
Name: deficiency_causes, dtype: int64

In [71]:
'''Dictionary for mapping values'''
clean['deficiency_causes'] = clean['deficiency_causes'].replace({
    1: 'Nascença',
    2: 'Doença',
    3: 'Minas/guerra',
    4: 'Serviço militar',
    5: 'Acidente de trabalho',
    6: 'Acidente de viação',
    98: 'Outros'

})

# Remove rows with zero counts (if any)
clean = clean[clean['deficiency_causes'] != 0]

# Now you can check the value counts
clean['deficiency_causes'].value_counts(dropna=False)

NaN                     2071870
Doença                    16156
Nascença                   7578
Outros                     1669
Acidente de viação         1626
Acidente de trabalho       1388
Minas/guerra                546
Serviço militar             258
Name: deficiency_causes, dtype: int64

**`mother_tongue:`**<br>
- 1	Bitonga
- 2	Cibalke
- 3	Cicopi
- 4	Cindau
- 5	Cinsenga
- 6	Cinyanja
- 7	Cinyungwe
- 8	Ciphimbi
- 9	Cisena
- 10	Citshwa
- 11	Echuwabo
- 12	Ekoti
- 13	Elomwe
- 14	Emakhuwa
- 15	Isizulu
- 16	Kimwani
- 17	Kiswahili
- 18	Português
- 19	Shimakonde
- 20	Siswati
- 21	Xingoni
- 22	Xirhonga
- 23	Xitsonga
- 24	Espanhol
- 25	Catalão
- 26	Françês
- 27	Inglês
- 28	Afrikhans
- 98	Outro

In [72]:
clean['mother_tongue'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2101091 entries, 0 to 2101090
Series name: mother_tongue
Non-Null Count    Dtype
--------------    -----
1073030 non-null  float64
dtypes: float64(1)
memory usage: 32.1 MB

In [73]:
clean['mother_tongue'].describe()

count    1.073030e+06
mean     2.457804e+01
std      1.537440e+01
min      1.000000e+00
25%      2.200000e+01
50%      2.200000e+01
75%      2.300000e+01
max      9.800000e+01
Name: mother_tongue, dtype: float64

In [74]:
clean['mother_tongue'].unique()

array([nan, 22., 23.,  1., 10., 98., 11.,  3.,  9., 14., 18.,  2., 13.,
        4., 21., 15., 17., 19.,  7., 16., 25., 20., 27., 24.,  6., 12.,
        5.,  8., 28., 26.])

In [75]:
clean['mother_tongue'].value_counts(dropna=False)

NaN     1028061
22.0     581484
23.0     382314
98.0      42798
10.0      20945
1.0       11225
11.0       8439
9.0        6993
3.0        5558
18.0       5006
14.0       2603
13.0       1249
4.0        1080
21.0        875
7.0         429
15.0        387
19.0        310
6.0         234
2.0         211
20.0        204
24.0        200
27.0        121
5.0          85
16.0         56
28.0         49
17.0         45
12.0         40
8.0          34
25.0         32
26.0         24
Name: mother_tongue, dtype: int64

In [76]:
'''Dictionary for mapping values'''
clean['mother_tongue'] = clean['mother_tongue'].replace({
    1: 'Bitonga',
    2: 'Cibalke',
    3: 'Cicopi',
    4: 'Cindau',
    5: 'Cinsenga',
    6: 'Cinyanja',
    7: 'Cinyungwe',
    8: 'Ciphimbi',
    9: 'Cisena',
    10: 'Citshwa',
    11: 'Echuwabo',
    12: 'Ekoti',
    13: 'Elomwe',
    14: 'Emakhuwa',
    15: 'Isizulu',
    16: 'Kimwani',
    17: 'Kiswahili',
    18: 'Português',
    19: 'Shimakonde',
    20: 'Siswati',
    21: 'Xingoni',
    22: 'Xirhonga',
    23: 'Xitsonga',
    24: 'Espanhol',
    25: 'Catalão',
    26: 'Françês',
    27: 'Inglês',
    28: 'Afrikhans',
    98: 'Outro'

})

# Remove rows with zero counts (if any)
clean = clean[clean['mother_tongue'] != 0]

# Now you can check the value counts
clean['mother_tongue'].value_counts(dropna=False)

NaN           1028061
Xirhonga       581484
Xitsonga       382314
Outro           42798
Citshwa         20945
Bitonga         11225
Echuwabo         8439
Cisena           6993
Cicopi           5558
Português        5006
Emakhuwa         2603
Elomwe           1249
Cindau           1080
Xingoni           875
Cinyungwe         429
Isizulu           387
Shimakonde        310
Cinyanja          234
Cibalke           211
Siswati           204
Espanhol          200
Inglês            121
Cinsenga           85
Kimwani            56
Afrikhans          49
Kiswahili          45
Ekoti              40
Ciphimbi           34
Catalão            32
Françês            24
Name: mother_tongue, dtype: int64

**`Convert Objects to Category:`**

In [77]:
#Convert all object type columns in your DataFrame to category
clean = clean.astype({col: 'category' for col in clean.select_dtypes(include='object').columns})

_____________
--------

**`Category:`**

In [78]:
#Describe category aswell
clean.describe(include='category')

,learning_place,event_date,mother_name,place_of_birth,deficiency_name,mother_perm_id,religion,secundary_ocupation,house_number,reason_to_not_update,spouse_name,education,secundary_ocupation_name,ocupation_name,event_place,mother_id,ocupation,marital_status,relation_with_head,perm_id,deficiency_causes_name,identity_doc_name,father_death_date,name,visit_id,deficiency_causes,mother_death_date,father_perm_id,mother_tongue,individual_id,gender_x,location_id,father_name,field_worker_id,father_id,spouse_perm_id,deficiency,uuid,extId,firstName,gender_y,lastName,father_uuid,mother_uuid
count,752122,821935,2100115,1943205,5690,2101091,1184474,899603,2101091,156008,269377,1418715,17894,53049,797976,2101091,1032006,1163014,1865289,2101091,1251,78678,75432,2101039,2101091,29221,30965,2101091,1073030,2101091,2101091,2101091,2100259,2101091,2101091,244748,29221,2101091,2101091,2101039,2101091,2101091,2101084,2101091
unique,5,14513,101340,22,2042,73160,12,24,59617,3,81730,25,1371,6504,6,73379,24,6,15,286234,442,484,5253,274463,453930,7,3629,40086,29,286772,2,59749,73512,105,40318,68455,10,295300,295295,274463,2,295277,35184,70393
top,Na Escola,2015-06-15 00:00:00.000,UNK,Distrito da Manhiça,MUDO,UNK,Zione/ Sião,Não tem,2606-019,O membro emigrou para ouro agregado não locali...,GONCALVES JOSE MUTACATE,Alfabetização 1º,DOMESTICA,BISCATEIRO,Distrito da Manhiça,UNK,Camponês,União-de-facto,Filho/a,9999-999-99,IDADE AVANCADA,NENHUM,2015-06-15 00:00:00,UNK,NWD000006044,Doença,2015-06-15 00:00:00,UNK,Xirhonga,TSF000017002,F,TSF000017,UNK,FWER1,UNK,0601-015-10,Outro,ff80818154966b3a015498241d3e0be1,1AI000338008,UNK,F,9999-999-99,Unknown Individual,Unknown Individual
freq,751042,14367,839075,1583537,387,876274,400715,661901,574,117400,153,173374,7553,6038,711275,876274,509308,546831,711157,874,164,46998,2472,3069,97,16156,1190,1395944,581484,558,1149980,574,1329276,66227,1395944,144,5691,107,107,3069,1147122,874,1448137,917252

`event_date:`

In [79]:
#Convert to datetime
clean['event_date'] = pd.to_datetime(clean['event_date'], errors='coerce')

`ids:`

In [80]:
clean['perm_id'].nunique()

286234

In [81]:
clean.describe(include='category')

,learning_place,mother_name,place_of_birth,deficiency_name,mother_perm_id,religion,secundary_ocupation,house_number,reason_to_not_update,spouse_name,education,secundary_ocupation_name,ocupation_name,event_place,mother_id,ocupation,marital_status,relation_with_head,perm_id,deficiency_causes_name,identity_doc_name,father_death_date,name,visit_id,deficiency_causes,mother_death_date,father_perm_id,mother_tongue,individual_id,gender_x,location_id,father_name,field_worker_id,father_id,spouse_perm_id,deficiency,uuid,extId,firstName,gender_y,lastName,father_uuid,mother_uuid
count,752122,2100115,1943205,5690,2101091,1184474,899603,2101091,156008,269377,1418715,17894,53049,797976,2101091,1032006,1163014,1865289,2101091,1251,78678,75432,2101039,2101091,29221,30965,2101091,1073030,2101091,2101091,2101091,2100259,2101091,2101091,244748,29221,2101091,2101091,2101039,2101091,2101091,2101084,2101091
unique,5,101340,22,2042,73160,12,24,59617,3,81730,25,1371,6504,6,73379,24,6,15,286234,442,484,5253,274463,453930,7,3629,40086,29,286772,2,59749,73512,105,40318,68455,10,295300,295295,274463,2,295277,35184,70393
top,Na Escola,UNK,Distrito da Manhiça,MUDO,UNK,Zione/ Sião,Não tem,2606-019,O membro emigrou para ouro agregado não locali...,GONCALVES JOSE MUTACATE,Alfabetização 1º,DOMESTICA,BISCATEIRO,Distrito da Manhiça,UNK,Camponês,União-de-facto,Filho/a,9999-999-99,IDADE AVANCADA,NENHUM,2015-06-15 00:00:00,UNK,NWD000006044,Doença,2015-06-15 00:00:00,UNK,Xirhonga,TSF000017002,F,TSF000017,UNK,FWER1,UNK,0601-015-10,Outro,ff80818154966b3a015498241d3e0be1,1AI000338008,UNK,F,9999-999-99,Unknown Individual,Unknown Individual
freq,751042,839075,1583537,387,876274,400715,661901,574,117400,153,173374,7553,6038,711275,876274,509308,546831,711157,874,164,46998,2472,3069,97,16156,1190,1395944,581484,558,1149980,574,1329276,66227,1395944,144,5691,107,107,3069,1147122,874,1448137,917252

In [82]:
# Check for non-standard characters
non_standard_chars = clean[~clean[['perm_id','mother_perm_id','father_perm_id','spouse_perm_id' ]].apply(lambda x: x.str.match(r'^[0-9\-]+$')).all(axis=1)]
non_standard_chars

,learning_place,event_date,is_present,work_regime,mother_name,nr_of_husband_wives,dob_x,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,deficiency_name,fertility_nr_stillbirths,has_id_card,mother_perm_id,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,house_number,reason_to_not_update,spouse_name,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,secundary_ocupation_name,ocupation_name,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,mother_id,ocupation,marital_status,passport_exp_stat,relation_with_head,perm_id,has_driving_license,deficiency_causes_name,fertility_nr_alive_girls,identity_doc_name,father_death_date,name,mother_alive,visit_id,deficiency_causes,fertility_nr_pregnancies,end,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_death_date,father_perm_id,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,individual_id,head_lives_here,mother_lives_here,round_number,gender_x,location_id,father_name,age,field_worker_id,father_id,note_reading,fertility_nr_triplet_outcomes,spouse_perm_id,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,start,father_lives_here,uuid,dob_y,dobAspect,extId,firstName,gender_y,lastName,middleName,father_uuid,mother_uuid
0,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324040,NaN,NaN,2017-04-10 11:57:23,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,2.0,2.0,40,F,BRX000324,UNK,4.0,FWAM6,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,4.0,99.0,2017-04-10 13:56:55,2.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
1,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,2.0,3506-245-01,3506.0,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324046,NaN,NaN,2020-03-07 09:27:35,NaN,NaN,2.0,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,2.0,1.0,46,F,BRX000324,UNK,6.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,7.0,1.0,2020-03-07 11:27:06,1.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
2,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,Filho/a,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324039,NaN,NaN,2016-12-01 23:08:22,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,1.0,1.0,39,F,BRX000324,UNK,3.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,2016-12-01 18:07:59,1.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
3,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324045,NaN,NaN,2019-08-26 12:39:55,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,2.0,1.0,45,F,BRX000324,UNK,6.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,7.0,2.0,2019-08-26 14:39:29,1.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
4,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,1.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,2ª Classe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,Filho/a,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324048,NaN,NaN,2022-04-22 13:53:16,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,1.0,1.0,48,F,BRX000324,UNK,9.0,FWTD1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,2022-04-22 15:52:50,2.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2101086,Na Escola,2020-09-03,2.0,2.0,UNK,NaN,1989-08-29,NaN,1.0,NaN,Zambézia,1.0,NaN,NaN,1.0,UNK,3407.0,1.0,NaN,NaN,NaN,2.0,Católica,1.0,1.0,Não tem,1.0,NaN,3407-053,NaN,NERCIA EGILISTO CARVALIO,NaN,9ª Classe,NaN,NaN,NaN,2.0,NaN,CUIDAR DA CASACE DOS ANIMAIS,NaN,NaN,1.0,NaN,Outras Provincias,1.0,1.0,1.0,2.0,UNK,Outro,União-de-facto,NaN,NaN,3407-053-09,2.0,NaN,NaN,NaN,NaT,MIQUIAS SIZINO SINGANO,NaN,7BB000053046,NaN,NaN,2020-09-03 11:39:37,NaN,NaN,2.0,NaT,UNK,Echuwabo,NaN,NaN,NaN,7BB000053010,2.0,NaN,46,M,7BB000053,UNK,31.0,FWCV1,UNK,NaN,NaN,3407-053-10,NaN,NaN,2.0,NaN,NaN,NaN,1.0,1.0,2020-09-03 13:38:17,NaN,2c906d7771f4b3e401747db04e1c2e7e,1989-08-29,1.0,7BB000053010,MIQUIAS SIZINO SINGANO,M,3407-053-09,NaN,Unknown Individual,Unknown Individual
2101087,Na Escola,NaT,1.0,1.0,CACILDA ALBINO MBEVE,NaN,1994-04-02,0.0,1.0,1.0,Distrito da Manhiça,2.0,NaN,0.0,1.0,3904-059-02,3904.0,1.0,NaN,NaN,0.0,2.0,Evangelica,NaN,NaN,Camponês,2.0,0.0,3904-059,NaN,NaN,NaN,8ª Classe,NaN,0.0,0.0,2.0,NaN,NaN,1.0,0.0,1.0,1.0,NaN,1.0,1.0,1.0,2.0,MAR000016002,Camponês,Solteiro (nunca viveu maritalmente),NaN,Enteado,3904-059-10,2.0,NaN,NaN,NaN,NaT,ILDA JAIME MULHOVO,NaN,MAR000016046,NaN,2.0,2020-03-25 18:01:26,1.0,NaN,2.0,NaT,UNK,Xirhonga,1.0,0.0,NaN,MAR000016010,1.0,NaN,46,F,MAR000016,UNK,25.0,FWJG1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,2020-03-25 19:57:21,NaN,2c906d77713040dd0171504182882b96,1994-04-02,1.0,MAR000016010,ILDA JAIME MULHOVO,F,3904-059-10,NaN,Unknown Individual,ff808181548e4cd30154958e11ac1a3e
2101088,NaN,2000-12-31,1.0,NaN,DEOLINDA LUCAS VIANA,NaN,1980-02-22,NaN,2.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3205-330-01,3203.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,1.0,NaN,NaN,NaN,NaN,3203-269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Distrito da Manhiça,NaN,1.0,1.0,2.0,1RR000182001,Não trabalha,União-de-facto,NaN,O Proprio chefe,3205-330-04,NaN,NaN,NaN,NaN,NaT,FERNANDO JUSTINO MAIACANA,NaN,3RC000265047,NaN,NaN,2021-05-11 09:51:08,NaN,NaN,NaN,NaT,UNK,Xirhonga,NaN,NaN,NaN,1RR000182004,1.0,NaN,47,M,3RC000265,UNK,41.0,FWER1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2021-05-11 11:50:31,NaN,ff8081815484e76b0154884724911bef,1980-02-22,NaN,1RR000182004,FERNANDO JUSTINO MAIACANA,M,3205-330-04,NaN,Unknown Individual,ff8081815484e76b015487cc301736c4
2101089,NaN,NaT,NaN,NaN,GILDA JAIME STOE,NaN,2009-05-02,NaN,NaN,NaN,Província de Maputo,NaN,NaN,NaN,NaN,3807-091-01,3807.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,NaN,NaN,NaN,NaN,NaN,3807-091,NaN,NaN,1.0,Alfabetização 1º,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,CIR000080001,NaN,NaN,NaN,Filho/a,3807-091-04,NaN,NaN,NaN,NaN,NaT,YUMINA TITOS MACAMO,1.0,CIR000080038,NaN,NaN,2015-10-14 16:10:01,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,CIR000080004,1.0,NaN,38,F,CIR000080,UNK,NaN,FWNC1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,2015-10-14 12:09:18,NaN,ff808181548e4cd301549430ea810876,2009-05-02,NaN,CIR000080004,YUMINA TITOS MACAMO,F,3807-091-04,NaN,Unknown Individual,ff808181548e4cd30154942e328406b9
2101090,NaN,2015-06-16,NaN,NaN,UNK,NaN,1941-10-10,NaN,NaN,NaN,Cidade de Maputo,NaN,NaN,NaN,NaN,UNK,2801.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,NaN,NaN,Outro,NaN,NaN,2801-089,NaN,NaN,NaN,Analfabeto / Nenhuma / Não escolarizado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2.0,UNK,Camponês,Viuvo,NaN,O Proprio chefe,2801-089-13,NaN,NaN,NaN,NaN,NaT,LUISA MUCHIPE MULUNGO,NaN,NWD000088038,NaN,NaN,2015-06-16 16:44:17,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,NWD000088007,1.0,NaN,38,F,NWD000088,UNK,NaN,FWFM1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2015-06-16 12:43:24,NaN,ff8081815484e76b01548bd04d25014f,1941-10-10,NaN,NWD000088007,LUISA MUCHIPE MULUNGO,F,2801-089-13,NaN,Unknown Individual,Unknown Individual

In [83]:
clean = clean[~clean[['perm_id', 'mother_perm_id', 'father_perm_id', 'spouse_perm_id']].apply(lambda col: col.str.endswith('HH')).any(axis=1)]

We have a alot of repeating columns, lets drop them:

In [84]:
clean.describe(include='category')

,learning_place,mother_name,place_of_birth,deficiency_name,mother_perm_id,religion,secundary_ocupation,house_number,reason_to_not_update,spouse_name,education,secundary_ocupation_name,ocupation_name,event_place,mother_id,ocupation,marital_status,relation_with_head,perm_id,deficiency_causes_name,identity_doc_name,father_death_date,name,visit_id,deficiency_causes,mother_death_date,father_perm_id,mother_tongue,individual_id,gender_x,location_id,father_name,field_worker_id,father_id,spouse_perm_id,deficiency,uuid,extId,firstName,gender_y,lastName,father_uuid,mother_uuid
count,750336,2073565,1935947,5673,2074536,1180650,896690,2074536,136736,267089,1414022,17846,52881,795275,2074536,1028718,1159403,1859124,2074536,1250,78349,75387,2074512,2074536,29172,30940,2074536,1069822,2074536,2074536,2074536,2073706,2074536,2074536,242500,29172,2074536,2074536,2074512,2074536,2074536,2074529,2074536
unique,5,101248,22,2037,73107,12,24,59234,3,81072,25,1368,6483,6,73324,24,6,15,282577,441,481,5253,272069,452805,7,3629,39101,29,283127,2,59368,72766,105,39234,67665,10,292375,292370,272069,2,292352,34989,70330
top,Na Escola,UNK,Distrito da Manhiça,MUDO,UNK,Zione/ Sião,Não tem,3602-192,O membro emigrou para ouro agregado não locali...,GONCALVES JOSE MUTACATE,Alfabetização 1º,DOMESTICA,BISCATEIRO,Distrito da Manhiça,UNK,Camponês,União-de-facto,Filho/a,9999-999-99,IDADE AVANCADA,NENHUM,2015-06-15 00:00:00,MARIA MANUEL COSSA,MCU000093041,Doença,2015-06-15 00:00:00,UNK,Xirhonga,NOV000139001,F,NOV000139,UNK,FWER1,UNK,0601-015-10,Outro,ff8081815484e76b015489fe77b87a0e,5BH000185003,MARIA MANUEL COSSA,F,9999-999-99,Unknown Individual,Unknown Individual
freq,749259,817389,1577154,387,854515,399353,659796,407,111627,153,172478,7540,6032,708745,854515,507709,544873,707777,874,164,46925,2472,1664,60,16136,1190,1374372,579575,204,1145836,407,1307792,65380,1374372,144,5674,107,107,1664,1141807,874,1424756,896589

In [85]:
clean.head(1)

,learning_place,event_date,is_present,work_regime,mother_name,nr_of_husband_wives,dob_x,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,deficiency_name,fertility_nr_stillbirths,has_id_card,mother_perm_id,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,house_number,reason_to_not_update,spouse_name,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,secundary_ocupation_name,ocupation_name,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,mother_id,ocupation,marital_status,passport_exp_stat,relation_with_head,perm_id,has_driving_license,deficiency_causes_name,fertility_nr_alive_girls,identity_doc_name,father_death_date,name,mother_alive,visit_id,deficiency_causes,fertility_nr_pregnancies,end,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_death_date,father_perm_id,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,individual_id,head_lives_here,mother_lives_here,round_number,gender_x,location_id,father_name,age,field_worker_id,father_id,note_reading,fertility_nr_triplet_outcomes,spouse_perm_id,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,start,father_lives_here,uuid,dob_y,dobAspect,extId,firstName,gender_y,lastName,middleName,father_uuid,mother_uuid
0,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506-245-01,3506.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324040,NaN,NaN,2017-04-10 11:57:23,NaN,NaN,NaN,NaT,UNK,NaN,NaN,NaN,NaN,BRX000324007,2.0,2.0,40,F,BRX000324,UNK,4.0,FWAM6,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,4.0,99.0,2017-04-10 13:56:55,2.0,ff80818154966b3a01549a14ac126156,2013-03-14,NaN,BRX000324007,ADINENCIA ANTONIO MUCARI,F,3506-245-07,NaN,Unknown Individual,ff80818154966b3a01549a1022bf601b

In [86]:
clean = clean.drop(columns=['mother_perm_id','father_perm_id', 'individual_id', 'uuid','mother_uuid', 'gender_y', 'uuid','extId','dob_y', 'dobAspect'])

In [87]:
# Check for duplicates
duplicates = clean[clean.duplicated(subset=['perm_id'], keep=False)]
duplicates

,learning_place,event_date,is_present,work_regime,mother_name,nr_of_husband_wives,dob_x,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,deficiency_name,fertility_nr_stillbirths,has_id_card,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,house_number,reason_to_not_update,spouse_name,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,secundary_ocupation_name,ocupation_name,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,mother_id,ocupation,marital_status,passport_exp_stat,relation_with_head,perm_id,has_driving_license,deficiency_causes_name,fertility_nr_alive_girls,identity_doc_name,father_death_date,name,mother_alive,visit_id,deficiency_causes,fertility_nr_pregnancies,end,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_death_date,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,head_lives_here,mother_lives_here,round_number,gender_x,location_id,father_name,age,field_worker_id,father_id,note_reading,fertility_nr_triplet_outcomes,spouse_perm_id,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,start,father_lives_here,firstName,lastName,middleName,father_uuid
0,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324040,NaN,NaN,2017-04-10 11:57:23,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2.0,2.0,40,F,BRX000324,UNK,4.0,FWAM6,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,4.0,99.0,2017-04-10 13:56:55,2.0,ADINENCIA ANTONIO MUCARI,3506-245-07,NaN,Unknown Individual
1,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,2.0,3506.0,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324046,NaN,NaN,2020-03-07 09:27:35,NaN,NaN,2.0,NaT,NaN,NaN,NaN,NaN,2.0,1.0,46,F,BRX000324,UNK,6.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,7.0,1.0,2020-03-07 11:27:06,1.0,ADINENCIA ANTONIO MUCARI,3506-245-07,NaN,Unknown Individual
2,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,Filho/a,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324039,NaN,NaN,2016-12-01 23:08:22,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,1.0,39,F,BRX000324,UNK,3.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,2016-12-01 18:07:59,1.0,ADINENCIA ANTONIO MUCARI,3506-245-07,NaN,Unknown Individual
3,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324045,NaN,NaN,2019-08-26 12:39:55,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2.0,1.0,45,F,BRX000324,UNK,6.0,FWJC2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,7.0,2.0,2019-08-26 14:39:29,1.0,ADINENCIA ANTONIO MUCARI,3506-245-07,NaN,Unknown Individual
4,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,1.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,2ª Classe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,Filho/a,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324048,NaN,NaN,2022-04-22 13:53:16,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,1.0,48,F,BRX000324,UNK,9.0,FWTD1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,2022-04-22 15:52:50,2.0,ADINENCIA ANTONIO MUCARI,3506-245-07,NaN,Unknown Individual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2101028,NaN,NaT,NaN,NaN,UNK,NaN,1970-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3003-037,O membro emigrou para ouro agregado não locali...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,UNK,NaN,NaN,NaN,NaN,3003-097-01,NaN,NaN,NaN,NaN,NaT,MARIA DANIEL SAMBO,NaN,MTK000051046,NaN,NaN,2020-06-30 13:44:33,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,46,F,MTK000051,UNK,50.0,FWEG1,UNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-06-30 15:44:27,NaN,MARIA DANIEL SAMBO,3003-097-01,NaN,Unknown Individual
2101029,NaN,NaT,NaN,NaN,UNK,NaN,1970-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3003-037,O membro emigrou para ouro agregado não locali...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,UNK,NaN,NaN,NaN,NaN,3003-097-01,NaN,NaN,NaN,NaN,NaT,MARIA DANIEL SAMBO,NaN,MTK000051046,NaN,NaN,2020-06-30 13:44:33,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,46,F,MTK000051,UNK,50.0,FWEG1,UNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-06-30 15:44:27,NaN,MARIA DANIEL SAMBO,3003-037-03,NaN,ff8081815484e76b01548689d25f4528
2101056,Na Escola,NaT,2.0,NaN,GINA JORGE ZITHA,NaN,1998-01-03,NaN,1.0,NaN,Inhambane,NaN,NaN,NaN,2.0,2406.0,1.0,NaN,NaN,NaN,2.0,Protestante/Anglicana,NaN,NaN,NaN,1.0,NaN,2406-228,NaN,NaN,NaN,7ª Classe,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,1.0,1.0,2.0,RIF000199001,Não trabalha,Solteiro (nunca viveu maritalmente),NaN,Filho/a,2405-299-02,2.0,NaN,NaN,NaN,NaT,CASTRO TIAGO MANGUE,NaN,RIG000231043,NaN,NaN,2018-08-14 09:11:06,NaN,NaN,2.0,NaT,Bitonga,NaN,NaN,NaN,1.0,NaN,43,M,RIG000231,UNK,20.0,FWMS1,UNK,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,1.0,2018-08-14 11:09:56,NaN,CASTRO TIAGO MANGUE,2405-299-02,NaN,Unknown Individual
2101065,NaN,1989-06-15,1.0,NaN,COTASSE UBISSE,NaN,1959-03-20,NaN,2.0,NaN,Distrito da Manhiça,1.0,NaN,NaN,1.0,3615.0,1.0,NaN,NaN,NaN,2.0,Protestante/Anglicana,NaN,NaN,Camponês,1.0,NaN,3615-163,NaN,SIMIAO XIRINDZA,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,2.0,NaN,Distrito da Manhiça,1.0,1.0,1.0,2.0,UNK,Reformado/pensionista,Separado,NaN,O Proprio chefe,3615-163-02,2.0,NaN,NaN,NaN,NaT,MARIETA MUNGONE COSSA,NaN,VEL000131048,NaN,NaN,2022-03-09 12:38:25,NaN,NaN,2.0,NaT,Xirhonga,NaN,NaN,NaN,1.0,NaN,48,F,VEL000131,MUNGONE COSSA,62.0,FWPC1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2022-03-09 14:34:49,NaN,MARIETA MUNGONE COSSA,3615-163-02,NaN,Unknown Individual
2101066,NaN,NaT,1.0,NaN,ELISA FRANCISCO SITOE,NaN,2016-10-04,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,2.0,3306.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,3306-064,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,1.0,1.0,NaN,GUG000044003,NaN,NaN,NaN,Neto/a,3306-064-03,2.0,NaN,NaN,CARTAO DE SAUDE,NaT,SONIA AFONSO NGUENHA,1.0,BR7000010040,NaN,NaN,2017-03-15 11:11:51,NaN,NaN,2.0,NaT,NaN,NaN,NaN,NaN,1.0,1.0,40,F,BR7000010,AFONSO JUNIOR NGUENHA,0.0,FWAS1,BR7000054004,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,1.0,2017-03-15 13:11:02,1.0,SONIA AFONSO NGUENHA,3306-090-02,NaN,Unknown Individual

In [88]:
# Inspect those duplicates
duplicates[['name','firstName', 'middleName', 'lastName', 'dob_x', 'place_of_birth', 'perm_id', 'event_date']]

,name,firstName,middleName,lastName,dob_x,place_of_birth,perm_id,event_date
0,ADINENCIA ANTONIO MUCARI,ADINENCIA ANTONIO MUCARI,NaN,3506-245-07,2013-03-14,Distrito da Manhiça,3506-245-07,NaT
1,ADINENCIA ANTONIO MUCARI,ADINENCIA ANTONIO MUCARI,NaN,3506-245-07,2013-03-14,Distrito da Manhiça,3506-245-07,NaT
2,ADINENCIA ANTONIO MUCARI,ADINENCIA ANTONIO MUCARI,NaN,3506-245-07,2013-03-14,Distrito da Manhiça,3506-245-07,NaT
3,ADINENCIA ANTONIO MUCARI,ADINENCIA ANTONIO MUCARI,NaN,3506-245-07,2013-03-14,Distrito da Manhiça,3506-245-07,NaT
4,ADINENCIA ANTONIO MUCARI,ADINENCIA ANTONIO MUCARI,NaN,3506-245-07,2013-03-14,Distrito da Manhiça,3506-245-07,NaT
...,...,...,...,...,...,...,...,...
2101028,MARIA DANIEL SAMBO,MARIA DANIEL SAMBO,NaN,3003-097-01,1970-05-15,NaN,3003-097-01,NaT
2101029,MARIA DANIEL SAMBO,MARIA DANIEL SAMBO,NaN,3003-037-03,1970-05-15,NaN,3003-097-01,NaT
2101056,CASTRO TIAGO MANGUE,CASTRO TIAGO MANGUE,NaN,2405-299-02,1998-01-03,Inhambane,2405-299-02,NaT
2101065,MARIETA MUNGONE COSSA,MARIETA MUNGONE COSSA,NaN,3615-163-02,1959-03-20,Distrito da Manhiça,3615-163-02,1989-06-15
2101066,SONIA AFONSO NGUENHA,SONIA AFONSO NGUENHA,NaN,3306-090-02,2016-10-04,Distrito da Manhiça,3306-064-03,NaT

In [89]:
#Drop firstName middleName lastName
clean = clean.drop(columns=['firstName','middleName','lastName'])

In [90]:
# Lets drop duplicates
clean = clean.drop_duplicates(subset=['perm_id'], keep='first')
clean

,learning_place,event_date,is_present,work_regime,mother_name,nr_of_husband_wives,dob_x,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,deficiency_name,fertility_nr_stillbirths,has_id_card,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,house_number,reason_to_not_update,spouse_name,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,secundary_ocupation_name,ocupation_name,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,mother_id,ocupation,marital_status,passport_exp_stat,relation_with_head,perm_id,has_driving_license,deficiency_causes_name,fertility_nr_alive_girls,identity_doc_name,father_death_date,name,mother_alive,visit_id,deficiency_causes,fertility_nr_pregnancies,end,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_death_date,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,head_lives_here,mother_lives_here,round_number,gender_x,location_id,father_name,age,field_worker_id,father_id,note_reading,fertility_nr_triplet_outcomes,spouse_perm_id,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,start,father_lives_here,father_uuid
0,NaN,NaT,1.0,NaN,MATILDE ANTONIO CHIRINDZA,NaN,2013-03-14,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3506.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3506-245,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,BRX000324001,NaN,NaN,NaN,NaN,3506-245-07,NaN,NaN,NaN,NaN,NaT,ADINENCIA ANTONIO MUCARI,1.0,BRX000324040,NaN,NaN,2017-04-10 11:57:23,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2.0,2.0,40,F,BRX000324,UNK,4.0,FWAM6,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,4.0,99.0,2017-04-10 13:56:55,2.0,Unknown Individual
11,Na Escola,NaT,1.0,1.0,ANA ALFREDO VALOI,NaN,1992-04-02,NaN,1.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,2.0,1802.0,1.0,NaN,NaN,NaN,2.0,Protestante/Anglicana,NaN,NaN,Não tem,2.0,NaN,1802-170,NaN,NaN,NaN,4ª Classe,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN,7.0,1.0,1.0,2.0,4BF000036002,Vendedores fixos,Solteiro (nunca viveu maritalmente),NaN,O Proprio chefe,0406-025-03,2.0,NaN,NaN,NaN,NaT,GRACA FRANCISCO MACHAVA,NaN,PHV000166043,NaN,NaN,2018-12-12 14:39:51,NaN,NaN,2.0,NaT,Xirhonga,1.0,NaN,NaN,1.0,NaN,43,F,PHV000166,ALBINO JOAO NHAZIMO,26.0,FWIX1,4BF000036001,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2018-12-12 16:27:07,NaN,ff8081815484e76b0154864a793d34c0
17,Na Escola,NaT,2.0,NaN,ANGELICA FILIPE MANDLATE,NaN,2005-12-11,NaN,1.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,2.0,3304.0,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,3304-152,NaN,NaN,2.0,5ª Classe,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN,2.0,1.0,1.0,NaN,BR5000152008,NaN,NaN,NaN,Filho/a,3304-138-10,NaN,NaN,NaN,NaN,2018-04-20,TANIA ANTONIO MACHAVA,1.0,BR5000115042,NaN,NaN,2018-04-20 11:30:21,NaN,NaN,2.0,NaT,NaN,NaN,NaN,NaN,1.0,1.0,42,F,BR5000115,UNK,12.0,FWAS1,UNK,NaN,NaN,NaN,NaN,2.0,2.0,NaN,1.0,NaN,NaN,1.0,2018-04-20 13:29:28,NaN,Unknown Individual
27,NaN,NaT,1.0,NaN,ANGELICA ESTEVAO MBOMBE,NaN,2011-07-30,NaN,1.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3304.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3304-206,NaN,NaN,1.0,3ª Classe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0,1.0,NaN,BR5000184004,NaN,NaN,NaN,Filho/a,3304-206-08,NaN,NaN,NaN,NaN,NaT,VANIA ARMANDO MACHAVA,1.0,BR5000169046,NaN,NaN,2020-03-11 09:28:38,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,1.0,46,F,BR5000169,ARMANDO ADRIANO MACHAVA,8.0,FWLB1,BR5000184002,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,2.0,2020-03-11 11:28:06,1.0,ff8081815484e76b0154887af237558d
31,NaN,NaT,1.0,NaN,CECILIA JORGE CUMAIO,NaN,1997-12-15,NaN,NaN,2.0,Distrito da Manhiça,1.0,NaN,NaN,1.0,3505.0,2.0,NaN,NaN,NaN,2.0,Protestante/Anglicana,NaN,NaN,Estudante,2.0,NaN,3505-165,NaN,NaN,NaN,2ª Classe,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,2.0,BRW000074001,Estudante,Solteiro (nunca viveu maritalmente),NaN,Filho/a,3505-165-04,2.0,NaN,NaN,NaN,NaT,VANIA ARMANDO MACHAVA,NaN,BRW000074039,NaN,NaN,2016-12-09 09:53:05,NaN,NaN,2.0,NaT,Xirhonga,NaN,NaN,NaN,1.0,NaN,39,F,BRW000074,UNK,18.0,FWCV1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2016-12-09 11:52:16,NaN,ff8081815484e76b0154887af237558d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2101086,Na Escola,2020-09-03,2.0,2.0,UNK,NaN,1989-08-29,NaN,1.0,NaN,Zambézia,1.0,NaN,NaN,1.0,3407.0,1.0,NaN,NaN,NaN,2.0,Católica,1.0,1.0,Não tem,1.0,NaN,3407-053,NaN,NERCIA EGILISTO CARVALIO,NaN,9ª Classe,NaN,NaN,NaN,2.0,NaN,CUIDAR DA CASACE DOS ANIMAIS,NaN,NaN,1.0,NaN,Outras Provincias,1.0,1.0,1.0,2.0,UNK,Outro,União-de-facto,NaN,NaN,3407-053-09,2.0,NaN,NaN,NaN,NaT,MIQUIAS SIZINO SINGANO,NaN,7BB000053046,NaN,NaN,2020-09-03 11:39:37,NaN,NaN,2.0,NaT,Echuwabo,NaN,NaN,NaN,2.0,NaN,46,M,7BB000053,UNK,31.0,FWCV1,UNK,NaN,NaN,3407-053-10,NaN,NaN,2.0,NaN,NaN,NaN,1.0,1.0,2020-09-03 13:38:17,NaN,Unknown Individual
2101087,Na Escola,NaT,1.0,1.0,CACILDA ALBINO MBEVE,NaN,1994-04-02,0.0,1.0,1.0,Distrito da Manhiça,2.0,NaN,0.0,1.0,3904.0,1.0,NaN,NaN,0.0,2.0,Evangelica,NaN,NaN,Camponês,2.0,0.0,3904-059,NaN,NaN,NaN,8ª Classe,NaN,0.0,0.0,2.0,NaN,NaN,1.0,0.0,1.0,1.0,NaN,1.0,1.0,1.0,2.0,MAR000016002,Camponês,Solteiro (nunca viveu maritalmente),NaN,Enteado,3904-059-10,2.0,NaN,NaN,NaN,NaT,ILDA JAIME MULHOVO,NaN,MAR000016046,NaN,2.0,2020-03-25 18:01:26,1.0,NaN,2.0,NaT,Xirhonga,1.0,0.0,NaN,1.0,NaN,46,F,MAR000016,UNK,25.0,FWJG1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,2020-03-25 19:57:21,NaN,Unknown Individual
2101088,NaN,2000-12-31,1.0,NaN,DEOLINDA LUCAS VIANA,NaN,1980-02-22,NaN,2.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3203.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,1.0,NaN,NaN,NaN,NaN,3203-269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Distrito da Manhiça,NaN,1.0,1.0,2.0,1RR000182001,Não trabalha,União-de-facto,NaN,O Proprio chefe,3205-330-04,NaN,NaN,NaN,NaN,NaT,FERNANDO JUSTINO MAIACANA,NaN,3RC000265047,NaN,NaN,2021-05-11 09:51:08,NaN,NaN,NaN,NaT,Xirhonga,NaN,NaN,NaN,1.0,NaN,47,M,3RC000265,UNK,41.0,FWER1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2021-05-11 11:50:31,NaN,Unknown Individual
2101089,NaN,NaT,NaN,NaN,GILDA JAIME STOE,NaN,2009-05-02,NaN,NaN,NaN,Província de Maputo,NaN,NaN,NaN,NaN,3807.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,NaN,NaN,NaN,NaN,NaN,3807-091,NaN,NaN,1.0,Alfabetização 1º,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,CIR000080001,NaN,NaN,NaN,Filho/a,3807-091-04,NaN,NaN,NaN,NaN,NaT,YUMINA TITOS MACAMO,1.0,CIR000080038,NaN,NaN,2015-10-14 16:10:01,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,38,F,CIR000080,UNK,NaN,FWNC1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,2015-10-14 12:09:18,NaN,Unknown Individual
2101090,NaN,2015-06-16,NaN,NaN,UNK,NaN,1941-10-10,NaN,NaN,NaN,Cidade de Maputo,NaN,NaN,NaN,NaN,2801.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,NaN,NaN,Outro,NaN,NaN,2801-089,NaN,NaN,NaN,Analfabeto / Nenhuma / Não escolarizado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2.0,UNK,Camponês,Viuvo,NaN,O Proprio chefe,2801-089-13,NaN,NaN,NaN,NaN,NaT,LUISA MUCHIPE MULUNGO,NaN,NWD000088038,NaN,NaN,2015-06-16 16:44:17,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,38,F,NWD000088,UNK,NaN,FWFM1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2015-06-16 12:43:24,NaN,Unknown Individual

In [91]:
clean['perm_id'].nunique()

282577

`Gender:`

In [92]:
clean['gender_x'].describe()

count     282577
unique         2
top            F
freq      153009
Name: gender_x, dtype: object

In [93]:
clean['gender_x'].info()

<class 'pandas.core.series.Series'>
Int64Index: 282577 entries, 0 to 2101090
Series name: gender_x
Non-Null Count   Dtype
--------------   -----
282577 non-null  category
dtypes: category(1)
memory usage: 2.4 MB

In [94]:
clean['gender_x'].value_counts(dropna=False)

F    153009
M    129568
Name: gender_x, dtype: int64

In [95]:
# standardize values
clean['gender_x'] = clean['gender_x'].str.lower()

In [96]:
#change name
clean.rename(columns={'gender_x': 'gender'}, inplace=True)

In [97]:
clean['gender'].value_counts(dropna=False)

f    153009
m    129568
Name: gender, dtype: int64

_____
___

**`Datetime:`**

In [98]:
#Describe datetime
clean.describe(include='datetime64[ns]')

,event_date,dob_x,end,start
count,99921,282574,282399,282577
unique,8741,27757,281279,281422
top,2015-06-15 00:00:00,1970-01-01 00:00:00,2018-08-13 14:24:38,2018-09-06 11:20:21
freq,1814,527,3,3
first,1900-06-15 00:00:00,1900-02-01 00:00:00,2010-01-01 10:22:10,2010-01-01 12:21:42
last,2023-02-09 00:00:00,2023-03-16 00:00:00,2023-02-09 10:06:14,2023-02-09 12:04:23

In [99]:
# Convert dates which are categorical
# Parse dates separately
parse_dates = ['father_death_date','mother_death_date']

# Apply dtypes and parse_dates to df
clean[parse_dates] = clean[parse_dates].apply(pd.to_datetime, errors='coerce')

`start, end, event_date:`

In [100]:
# check min, max of start, end, event_date
print(f'start min:', clean['start'].min())
print(f'start max:', clean['start'].max())
print(f'_____________________________')

print(f'end min:', clean['end'].min())
print(f'end max:', clean['end'].max())
print(f'_____________________________')

print(f'event_date min:', clean['event_date'].min())
print(f'event_date max:', clean['event_date'].max())
print(f'_____________________________')

start min: 2010-01-01 12:21:42
start max: 2023-02-09 12:04:23
_____________________________
end min: 2010-01-01 10:22:10
end max: 2023-02-09 10:06:14
_____________________________
event_date min: 1900-06-15 00:00:00
event_date max: 2023-02-09 00:00:00
_____________________________

In [101]:
#Event_Date has years below 1996, we need to drop them
clean[clean['event_date'] < '1996-01-01']

,learning_place,event_date,is_present,work_regime,mother_name,nr_of_husband_wives,dob_x,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,deficiency_name,fertility_nr_stillbirths,has_id_card,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,house_number,reason_to_not_update,spouse_name,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,secundary_ocupation_name,ocupation_name,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,mother_id,ocupation,marital_status,passport_exp_stat,relation_with_head,perm_id,has_driving_license,deficiency_causes_name,fertility_nr_alive_girls,identity_doc_name,father_death_date,name,mother_alive,visit_id,deficiency_causes,fertility_nr_pregnancies,end,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_death_date,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,head_lives_here,mother_lives_here,round_number,gender,location_id,father_name,age,field_worker_id,father_id,note_reading,fertility_nr_triplet_outcomes,spouse_perm_id,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,start,father_lives_here,father_uuid
72,NaN,1990-06-15,1.0,1.0,UNK,1.0,1962-02-16,NaN,NaN,NaN,Distrito da Manhiça,1.0,NaN,NaN,1.0,3609.0,1.0,NaN,NaN,NaN,2.0,Protestante/Anglicana,NaN,NaN,Outro,2.0,NaN,3609-201,NaN,MANUEL JUSTINO ELEFANTE,NaN,Analfabeto / Nenhuma / Não escolarizado,NaN,NaN,NaN,2.0,DOMESTICA,NaN,2.0,NaN,2.0,NaN,Distrito da Manhiça,1.0,1.0,1.0,2.0,UNK,Camponês,Casado,NaN,Esposo/a,3609-201-02,2.0,NaN,NaN,NaN,NaT,FLORINDA TSAMELE COSSA,NaN,CIN000213040,NaN,NaN,2017-03-31 07:35:40,NaN,NaN,2.0,NaT,Xitsonga,1.0,NaN,NaN,1.0,NaN,40,f,CIN000213,UNK,55.0,FWLL1,UNK,NaN,NaN,3609-201-01,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2017-03-31 09:34:37,NaN,Unknown Individual
116,NaN,1995-05-10,1.0,1.0,UNK,1.0,1977-05-13,NaN,2.0,NaN,Distrito da Manhiça,1.0,NaN,NaN,1.0,3209.0,2.0,NaN,NaN,NaN,2.0,Cristão indeterminada,NaN,NaN,Não tem,2.0,NaN,3209-057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,2.0,NaN,Distrito da Manhiça,1.0,1.0,1.0,2.0,UNK,Camponês,União-de-facto,NaN,O Proprio chefe,3209-057-01,2.0,NaN,NaN,NaN,NaT,MARTA ALFREDO MAFAI,NaN,7BA000009048,NaN,NaN,2022-03-14 14:42:22,NaN,NaN,2.0,NaT,Xirhonga,1.0,NaN,NaN,1.0,NaN,48,f,7BA000009,UNK,44.0,FWER1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2022-03-14 16:41:31,NaN,Unknown Individual
362,NaN,1995-01-15,2.0,1.0,CECILIA JOSE CHIRINDZA,NaN,1977-06-15,NaN,2.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,2.0,3210.0,1.0,NaN,NaN,NaN,2.0,Zione/ Sião,1.0,NaN,Não tem,2.0,NaN,3210-357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,Distrito da Manhiça,7.0,1.0,1.0,2.0,6BA000324001,Camponês,União-de-facto,NaN,O Proprio chefe,3210-357-01,2.0,NaN,NaN,NaN,NaT,ALBERTO FRANCISCO BOANE,NaN,6BA000324046,NaN,NaN,2020-05-28 13:10:18,NaN,NaN,2.0,NaT,Xirhonga,1.0,NaN,NaN,1.0,NaN,46,m,6BA000324,UNK,42.0,FWER1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2020-05-28 15:09:29,NaN,Unknown Individual
507,NaN,1976-06-10,1.0,1.0,UNK,1.0,1956-10-27,NaN,1.0,NaN,Gaza,1.0,NaN,NaN,1.0,2901.0,1.0,NaN,NaN,NaN,2.0,Zione/ Sião,NaN,NaN,Não tem,2.0,NaN,2901-130,NaN,INANCIO MUNGANDO,NaN,2ª Classe,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,2.0,NaN,Distrito da Manhiça,1.0,1.0,1.0,2.0,UNK,Camponês,União-de-facto,NaN,O Proprio chefe,2901-130-01,2.0,NaN,NaN,NaN,NaT,ADELIA AZARIAS MULHANGA,NaN,MCN000128048,NaN,NaN,2022-10-27 10:54:04,NaN,NaN,2.0,NaT,Xirhonga,1.0,NaN,NaN,1.0,NaN,48,f,MCN000128,UNK,66.0,FWGM2,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2022-10-27 12:51:41,NaN,Unknown Individual
1441,NaN,1975-06-15,1.0,1.0,UNK,NaN,1944-08-01,NaN,1.0,NaN,Distrito da Manhiça,1.0,NaN,NaN,1.0,3810.0,1.0,NaN,NaN,NaN,2.0,Zione/ Sião,1.0,NaN,Não tem,2.0,NaN,3810-142,NaN,JOANA DZECO,NaN,2ª Classe,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,Distrito da Manhiça,1.0,1.0,1.0,2.0,UNK,Camponês,Casado,NaN,O Proprio chefe,3810-142-01,2.0,NaN,NaN,NaN,NaT,ALBERTO LUIS MELEMBE,NaN,CRN000166048,NaN,NaN,2022-09-12 13:05:23,NaN,NaN,2.0,NaT,Xitsonga,1.0,NaN,NaN,1.0,NaN,48,m,CRN000166,UNK,78.0,FWAC2,UNK,NaN,NaN,3810-142-02,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2022-09-12 14:59:58,NaN,Unknown Individual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2100158,Na Escola,1994-06-15,1.0,NaN,UNK,NaN,1955-08-06,NaN,1.0,NaN,Inhambane,1.0,NaN,NaN,1.0,3802.0,1.0,NaN,NaN,NaN,2.0,Católica,1.0,NaN,Camponês,2.0,NaN,3802-754,NaN,NaN,NaN,7ª Classe,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,Maputo,1.0,1.0,1.0,2.0,UNK,Reformado/pensionista,União-de-facto,NaN,O Proprio chefe,3802-754-01,2.0,NaN,NaN,NaN,NaT,AMOS LINDELA NHACUONGA,NaN,IIBIM1009048,NaN,NaN,2022-04-20 11:25:58,NaN,NaN,2.0,NaT,Cicopi,NaN,NaN,NaN,1.0,NaN,48,m,IIBIM1009,UNK,66.0,FWAC2,UNK,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2022-04-20 13:16:25,NaN,Unknown Individual
2100503,Na Escola,1979-12-08,1.0,2.0,UNK,NaN,1953-03-27,NaN,1.0,NaN,Gaza,1.0,NaN,NaN,1.0,1603.0,1.0,NaN,NaN,NaN,2.0,Protestante/Anglicana,1.0,1.0,Camponês,1.0,NaN,1603-213,NaN,PALMIRA JULIO MACHAVA,NaN,12ª Classe,NaN,NaN,NaN,2.0,NaN,PASTOR,NaN,NaN,1.0,NaN,Outras Provincias,1.0,1.0,1.0,2.0,UNK,Outro,União-de-facto,NaN,O Proprio chefe,1603-071-09,2.0,NaN,NaN,NaN,NaT,SALOMAO ESTEVAO ZITHA,NaN,3BGAM5006048,NaN,NaN,2022-07-18 11:54:53,NaN,NaN,2.0,NaT,Xirhonga,NaN,NaN,NaN,1.0,NaN,48,m,3BGAM5006,UNK,69.0,FWAM5,UNK,NaN,NaN,1603-071-10,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2022-07-18 13:53:56,NaN,Unknown Individual
2100765,NaN,1979-06-15,1.0,1.0,UNK,NaN,1954-08-01,NaN,NaN,NaN,Distrito da Manhiça,1.0,NaN,NaN,1.0,3905.0,2.0,NaN,NaN,NaN,2.0,Católica,1.0,NaN,Camponês,2.0,NaN,3905-061,NaN,OLGA RAFAEL ZITA,NaN,Alfabetização 1º,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,Distrito da Manhiça,1.0,1.0,1.0,2.0,UNK,Camponês,União-de-facto,NaN,O Proprio chefe,3905-061-01,2.0,NaN,NaN,NaN,NaT,CÉSAR JOSÉ DIMANDE,NaN,CEC000230040,NaN,NaN,2017-07-11 10:07:07,NaN,NaN,2.0,NaT,Xirhonga,1.0,NaN,NaN,1.0,NaN,40,m,CEC000230,UNK,62.0,FWJG1,UNK,NaN,NaN,3905-061-02,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2017-07-11 12:05:26,NaN,Unknown Individual
2100934,Na Escola,1985-06-15,1.0,1.0,UNK,NaN,1960-09-07,NaN,1.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,2.0,3203.0,2.0,NaN,NaN,NaN,2.0,Zione/ Sião,1.0,NaN,Não tem,2.0,NaN,3203-287,NaN,LINA EUGENIO MAPOSSE,NaN,6ª Classe,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,Distrito da Manhiça,5.0,1.0,1.0,2.0,UNK,Camponês,União-de-facto,1.0,O Proprio chefe,3203-287-05,2.0,NaN,NaN,NaN,NaT,SAMUEL ARMANDO MBOANE,NaN,3RC000281046,NaN,NaN,2020-07-27 09:33:19,NaN,NaN,2.0,NaT,Xirhonga,1.0,NaN,NaN,1.0,NaN,46,m,3RC000281,UNK,59.0,FWER1,UNK,NaN,NaN,3203-260-01,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2020-07-27 11:32:34,NaN,Unknown Individual
2101081,NaN,1994-06-15,NaN,NaN,MARIA SILVA NGUENHA,NaN,1982-06-15,NaN,NaN,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3301.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,NaN,NaN,Não tem,NaN,NaN,3301-043,NaN,NaN,NaN,Analfabeto / Nenhuma / Não escolarizado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Distrito da Manhiça,NaN,NaN,1.0,2.0,1DM000101001,Camponês,Viuvo,NaN,Irmao/a,3301-043-12,NaN,NaN,NaN,NaN,NaT,ADELIA FRANCISCO MACUIANA,NaN,BR1000116038,NaN,NaN,2015-07-25 12:42:37,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,38,f,BR1000116,UNK,NaN,FWTM1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2015-07-25 14:39:37,NaN,Unknown Individual

In [102]:
# Define cutoff date
cutoff_date = pd.to_datetime('1996-01-01')

# Count unique dropped dates
unique_dropped_dates = clean['event_date'][clean['event_date'] < cutoff_date].nunique()
print(f'Unique dates dropped: {unique_dropped_dates}')

# Drop rows with 'event_date' before cutoff
clean = clean[clean['event_date'] > cutoff_date]

Unique dates dropped: 1658

In [103]:
# Ensure logical consistency - end_date not before start_date
if 'start' in clean.columns and 'end' in clean.columns:
    inconsistent_dates = clean[clean['end'] < clean['start']]

In [104]:
inconsistent_dates[['start','end', 'event_date']]

                      start                 end event_date
61      2019-09-03 16:21:55 2019-09-03 14:22:56 2019-09-03
83      2021-10-07 12:29:41 2021-10-07 10:31:07 2018-06-15
136     2019-10-30 18:15:38 2019-10-30 16:16:21 2019-10-30
158     2019-09-11 16:39:28 2019-09-11 14:40:24 2019-09-11
243     2015-10-21 12:19:26 2015-10-21 10:20:54 2015-10-21
...                     ...                 ...        ...
2101080 2022-03-01 10:15:18 2022-03-01 08:16:23 2022-03-01
2101082 2022-04-28 13:20:26 2022-04-28 11:21:59 2012-04-15
2101084 2022-07-04 12:19:39 2022-07-04 10:20:16 2022-07-04
2101086 2020-09-03 13:38:17 2020-09-03 11:39:37 2020-09-03
2101088 2021-05-11 11:50:31 2021-05-11 09:51:08 2000-12-31

[83917 rows x 3 columns]

What I noticed is that the only incosistency is the hours, minutes, and seconds and the dates are similiar. so we might say process only took a day, maybe due to the rounds. And event_date some dates are far from start and end, this might be due to the time the data has been collected, so we won't drop those dates because its a large number of rows. I will leave the dates and not drop them(for now).

In [105]:
# clean = clean.drop(inconsistent_dates.index)

`Date Of Birth(dob):`

In [106]:
clean[['dob_x']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92885 entries, 61 to 2101090
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   dob_x   92885 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.4 MB

In [107]:
print(clean['dob_x'].describe())
print(f'______________________________')
print(f'dob_x min:', clean['dob_x'].min())
print(f'dob_X max:', clean['dob_x'].max())
print(f'______________________________')

count                   92885
unique                  20456
top       1970-01-01 00:00:00
freq                      404
first     1900-02-01 00:00:00
last      2015-06-09 00:00:00
Name: dob_x, dtype: object
______________________________
dob_x min: 1900-02-01 00:00:00
dob_X max: 2015-06-09 00:00:00
______________________________

In [108]:
# Check for outliers(dates too far in the past or future)
min_date = pd.Timestamp('1900-01-01')
max_date = pd.Timestamp('2024-12-31')

In [109]:
outliers = clean[(clean['dob_x'] < min_date ) | (clean['dob_x'] > max_date)]
outliers

Empty DataFrame
Columns: [learning_place, event_date, is_present, work_regime, mother_name, nr_of_husband_wives, dob_x, fertility_nr_girls, has_education, fertility_has_prev_pregnancies, place_of_birth, id_exp_stat, deficiency_name, fertility_nr_stillbirths, has_id_card, region, has_voter_card, non_work_days, card_state, fertility_nr_twin_abortions, has_birth_certificate, religion, nr_of_wives, works_for_others, secundary_ocupation, has_cedula, fertility_nr_miscarriages, house_number, reason_to_not_update, spouse_name, father_alive, education, reading_quality, fertility_nr_abortions, fertility_nr_twin_outcomes, has_passport, secundary_ocupation_name, ocupation_name, has_fertility, fertility_nr_twin_stillbirths, can_read_write, fertility_nr_boys, event_place, identity_doc_type, is_updatable, consent, stopped_work_last_month, mother_id, ocupation, marital_status, passport_exp_stat, relation_with_head, perm_id, has_driving_license, deficiency_causes_name, fertility_nr_alive_girls, identity_doc_name, father_death_date, name, mother_alive, visit_id, deficiency_causes, fertility_nr_pregnancies, end, fertility_nr_livebirths, driv_license_exp_stat, has_id_receipt, mother_death_date, mother_tongue, self_employed, fertility_nr_twins_alive, wives_on_same_house, head_lives_here, mother_lives_here, round_number, gender, location_id, father_name, age, field_worker_id, father_id, note_reading, fertility_nr_triplet_outcomes, spouse_perm_id, fertility_nr_quadr_outcomes, can_test_reading, has_deficiency, deficiency, has_cism_card, fertility_nr_alive_boys, relation_with_subs_head, has_identity_doc, start, father_lives_here, father_uuid]
Index: []

In [110]:
#Rename the dob_x to dob
clean.rename(columns={'dob_x': 'dob'}, inplace=True)

### Lets check if we missed anything:

In [111]:
clean.tail()

,learning_place,event_date,is_present,work_regime,mother_name,nr_of_husband_wives,dob,fertility_nr_girls,has_education,fertility_has_prev_pregnancies,place_of_birth,id_exp_stat,deficiency_name,fertility_nr_stillbirths,has_id_card,region,has_voter_card,non_work_days,card_state,fertility_nr_twin_abortions,has_birth_certificate,religion,nr_of_wives,works_for_others,secundary_ocupation,has_cedula,fertility_nr_miscarriages,house_number,reason_to_not_update,spouse_name,father_alive,education,reading_quality,fertility_nr_abortions,fertility_nr_twin_outcomes,has_passport,secundary_ocupation_name,ocupation_name,has_fertility,fertility_nr_twin_stillbirths,can_read_write,fertility_nr_boys,event_place,identity_doc_type,is_updatable,consent,stopped_work_last_month,mother_id,ocupation,marital_status,passport_exp_stat,relation_with_head,perm_id,has_driving_license,deficiency_causes_name,fertility_nr_alive_girls,identity_doc_name,father_death_date,name,mother_alive,visit_id,deficiency_causes,fertility_nr_pregnancies,end,fertility_nr_livebirths,driv_license_exp_stat,has_id_receipt,mother_death_date,mother_tongue,self_employed,fertility_nr_twins_alive,wives_on_same_house,head_lives_here,mother_lives_here,round_number,gender,location_id,father_name,age,field_worker_id,father_id,note_reading,fertility_nr_triplet_outcomes,spouse_perm_id,fertility_nr_quadr_outcomes,can_test_reading,has_deficiency,deficiency,has_cism_card,fertility_nr_alive_boys,relation_with_subs_head,has_identity_doc,start,father_lives_here,father_uuid
2101082,Na Escola,2012-04-15,1.0,1.0,UNK,1.0,1990-07-10,1.0,1.0,1.0,Cidade de Maputo,1.0,NaN,0.0,1.0,3103.0,1.0,NaN,NaN,0.0,1.0,Cristão indeterminada,NaN,NaN,Não tem,2.0,0.0,3103-119,NaN,NaN,NaN,9ª Classe,NaN,0.0,0.0,2.0,NaN,NaN,1.0,0.0,1.0,2.0,Maputo,1.0,1.0,1.0,2.0,UNK,Camponês,União-de-facto,NaN,O Proprio chefe,3103-119-08,2.0,NaN,1.0,NaN,NaT,ENERALDA NHIRITA MAVIE,NaN,3BI000125048,NaN,3.0,2022-04-28 11:21:59,3.0,NaN,2.0,NaT,Xirhonga,1.0,0.0,NaN,1.0,NaN,48,f,3BI000125,UNK,31.0,FWER1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,2022-04-28 13:20:26,NaN,Unknown Individual
2101084,NaN,2022-07-04,2.0,2.0,UNK,NaN,1980-06-15,NaN,2.0,NaN,Província de Maputo,NaN,NaN,NaN,NaN,3609.0,NaN,NaN,NaN,NaN,NaN,Ateus,NaN,1.0,Empregado doméstico,NaN,NaN,3609-273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Distrito da Manhiça,NaN,1.0,2.0,2.0,UNK,Empregado doméstico,Separado,NaN,Enteado,3609-273-12,NaN,NaN,NaN,NaN,NaT,ISAC JULIO MONGUE,NaN,CIN000176048,NaN,NaN,2022-07-04 10:20:16,NaN,NaN,NaN,NaT,Xitsonga,NaN,NaN,NaN,1.0,NaN,48,m,CIN000176,UNK,42.0,FWNX1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,99.0,2022-07-04 12:19:39,NaN,Unknown Individual
2101086,Na Escola,2020-09-03,2.0,2.0,UNK,NaN,1989-08-29,NaN,1.0,NaN,Zambézia,1.0,NaN,NaN,1.0,3407.0,1.0,NaN,NaN,NaN,2.0,Católica,1.0,1.0,Não tem,1.0,NaN,3407-053,NaN,NERCIA EGILISTO CARVALIO,NaN,9ª Classe,NaN,NaN,NaN,2.0,NaN,CUIDAR DA CASACE DOS ANIMAIS,NaN,NaN,1.0,NaN,Outras Provincias,1.0,1.0,1.0,2.0,UNK,Outro,União-de-facto,NaN,NaN,3407-053-09,2.0,NaN,NaN,NaN,NaT,MIQUIAS SIZINO SINGANO,NaN,7BB000053046,NaN,NaN,2020-09-03 11:39:37,NaN,NaN,2.0,NaT,Echuwabo,NaN,NaN,NaN,2.0,NaN,46,m,7BB000053,UNK,31.0,FWCV1,UNK,NaN,NaN,3407-053-10,NaN,NaN,2.0,NaN,NaN,NaN,1.0,1.0,2020-09-03 13:38:17,NaN,Unknown Individual
2101088,NaN,2000-12-31,1.0,NaN,DEOLINDA LUCAS VIANA,NaN,1980-02-22,NaN,2.0,NaN,Distrito da Manhiça,NaN,NaN,NaN,NaN,3203.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,1.0,NaN,NaN,NaN,NaN,3203-269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Distrito da Manhiça,NaN,1.0,1.0,2.0,1RR000182001,Não trabalha,União-de-facto,NaN,O Proprio chefe,3205-330-04,NaN,NaN,NaN,NaN,NaT,FERNANDO JUSTINO MAIACANA,NaN,3RC000265047,NaN,NaN,2021-05-11 09:51:08,NaN,NaN,NaN,NaT,Xirhonga,NaN,NaN,NaN,1.0,NaN,47,m,3RC000265,UNK,41.0,FWER1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2021-05-11 11:50:31,NaN,Unknown Individual
2101090,NaN,2015-06-16,NaN,NaN,UNK,NaN,1941-10-10,NaN,NaN,NaN,Cidade de Maputo,NaN,NaN,NaN,NaN,2801.0,NaN,NaN,NaN,NaN,NaN,Zione/ Sião,NaN,NaN,Outro,NaN,NaN,2801-089,NaN,NaN,NaN,Analfabeto / Nenhuma / Não escolarizado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2.0,UNK,Camponês,Viuvo,NaN,O Proprio chefe,2801-089-13,NaN,NaN,NaN,NaN,NaT,LUISA MUCHIPE MULUNGO,NaN,NWD000088038,NaN,NaN,2015-06-16 16:44:17,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,38,f,NWD000088,UNK,NaN,FWFM1,UNK,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2015-06-16 12:43:24,NaN,Unknown Individual

&#128077; Okay, everything looks fine. We can save the dataset and move on to visualization. If we missed anything, we can always clean or fix it when we visualize.

In [112]:
clean.to_csv('clean.csv')